[package]
name = "icons"
version = "0.1.0"
edition = "2021"
authors = ["Cosmo André <soucosmomoraes@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.12"
iced-box = { version = "0.3.0", features = ["icon"] }
