use std::fmt::Display;
use iced::font::Font;

/// ### A module that allows the use of [Lucide](https://lucide.dev/icons) icons in a simplified way, see all the icons that can be used on the official page <https://lucide.dev/icons>
/// #### Example of use
/// ```rust
/// use iced::widget::{text, button};
/// 
/// use iced_box::icon::lucide::{Lucide, lucide_font, load_lucide_font};
/// 
/// let lucide_font = lucide_font();
/// 
/// text(Lucide::Anchor).font(lucide_font);
/// 
/// button(
///     text(Lucide::Anchor).font(lucide_font)
/// );
/// ```
/// 
/// Just provide the same name as CamelCase.
/// 
/// A complete example can be seen [here](https://github.com/iced-box/iced-box/tree/main/examples/icons)
/// 
/// 

pub enum Lucide {
    AArrowDown,
    AArrowUp,
    ALargeSmall,
    Accessibility,
    Activity,
    AirVent,
    Airplay,
    AlarmClockCheck,
    AlarmClockMinus,
    AlarmClockOff,
    AlarmClockPlus,
    AlarmClock,
    AlarmSmoke,
    Album,
    AlignCenterHorizontal,
    AlignCenterVertical,
    AlignCenter,
    AlignEndHorizontal,
    AlignEndVertical,
    AlignHorizontalDistributeCenter,
    AlignHorizontalDistributeEnd,
    AlignHorizontalDistributeStart,
    AlignHorizontalJustifyCenter,
    AlignHorizontalJustifyEnd,
    AlignHorizontalJustifyStart,
    AlignHorizontalSpaceAround,
    AlignHorizontalSpaceBetween,
    AlignJustify,
    AlignLeft,
    AlignRight,
    AlignStartHorizontal,
    AlignStartVertical,
    AlignVerticalDistributeCenter,
    AlignVerticalDistributeEnd,
    AlignVerticalDistributeStart,
    AlignVerticalJustifyCenter,
    AlignVerticalJustifyEnd,
    AlignVerticalJustifyStart,
    AlignVerticalSpaceAround,
    AlignVerticalSpaceBetween,
    Ambulance,
    Ampersand,
    Ampersands,
    Anchor,
    Angry,
    Annoyed,
    Antenna,
    Anvil,
    Aperture,
    AppWindowMac,
    AppWindow,
    Apple,
    ArchiveRestore,
    ArchiveX,
    Archive,
    AreaChart,
    Armchair,
    ArrowBigDownDash,
    ArrowBigDown,
    ArrowBigLeftDash,
    ArrowBigLeft,
    ArrowBigRightDash,
    ArrowBigRight,
    ArrowBigUpDash,
    ArrowBigUp,
    ArrowDown01,
    ArrowDown10,
    ArrowDownAZ,
    ArrowDownFromLine,
    ArrowDownLeft,
    ArrowDownNarrowWide,
    ArrowDownRight,
    ArrowDownToDot,
    ArrowDownToLine,
    ArrowDownUp,
    ArrowDownWideNarrow,
    ArrowDownZA,
    ArrowDown,
    ArrowLeftFromLine,
    ArrowLeftRight,
    ArrowLeftToLine,
    ArrowLeft,
    ArrowRightFromLine,
    ArrowRightLeft,
    ArrowRightToLine,
    ArrowRight,
    ArrowUp01,
    ArrowUp10,
    ArrowUpAZ,
    ArrowUpDown,
    ArrowUpFromDot,
    ArrowUpFromLine,
    ArrowUpLeft,
    ArrowUpNarrowWide,
    ArrowUpRight,
    ArrowUpToLine,
    ArrowUpWideNarrow,
    ArrowUpZA,
    ArrowUp,
    ArrowsUpFromLine,
    Asterisk,
    AtSign,
    Atom,
    AudioLines,
    AudioWaveform,
    Award,
    Axe,
    Axis3D,
    Baby,
    Backpack,
    BadgeAlert,
    BadgeCent,
    BadgeCheck,
    BadgeDollarSign,
    BadgeEuro,
    BadgeHelp,
    BadgeIndianRupee,
    BadgeInfo,
    BadgeJapaneseYen,
    BadgeMinus,
    BadgePercent,
    BadgePlus,
    BadgePoundSterling,
    BadgeRussianRuble,
    BadgeSwissFranc,
    BadgeX,
    Badge,
    BaggageClaim,
    Ban,
    Banana,
    Banknote,
    BarChart2,
    BarChart3,
    BarChart4,
    BarChartBig,
    BarChartHorizontalBig,
    BarChartHorizontal,
    BarChart,
    Barcode,
    Baseline,
    Bath,
    BatteryCharging,
    BatteryFull,
    BatteryLow,
    BatteryMedium,
    BatteryWarning,
    Battery,
    Beaker,
    BeanOff,
    Bean,
    BedDouble,
    BedSingle,
    Bed,
    Beef,
    BeerOff,
    Beer,
    BellDot,
    BellElectric,
    BellMinus,
    BellOff,
    BellPlus,
    BellRing,
    Bell,
    BetweenHorizontalEnd,
    BetweenHorizontalStart,
    BetweenVerticalEnd,
    BetweenVerticalStart,
    Bike,
    Binary,
    Biohazard,
    Bird,
    Bitcoin,
    Blend,
    Blinds,
    Blocks,
    BluetoothConnected,
    BluetoothOff,
    BluetoothSearching,
    Bluetooth,
    Bold,
    Bolt,
    Bomb,
    Bone,
    BookA,
    BookAudio,
    BookCheck,
    BookCopy,
    BookDashed,
    BookDown,
    BookHeadphones,
    BookHeart,
    BookImage,
    BookKey,
    BookLock,
    BookMarked,
    BookMinus,
    BookOpenCheck,
    BookOpenText,
    BookOpen,
    BookPlus,
    BookText,
    BookType,
    BookUp2,
    BookUp,
    BookUser,
    BookX,
    Book,
    BookmarkCheck,
    BookmarkMinus,
    BookmarkPlus,
    BookmarkX,
    Bookmark,
    BoomBox,
    BotMessageSquare,
    Bot,
    BoxSelect,
    Box,
    Boxes,
    Braces,
    Brackets,
    BrainCircuit,
    BrainCog,
    Brain,
    BrickWall,
    BriefcaseBusiness,
    BriefcaseMedical,
    Briefcase,
    BringToFront,
    Brush,
    BugOff,
    BugPlay,
    Bug,
    Building2,
    Building,
    BusFront,
    Bus,
    CableCar,
    Cable,
    CakeSlice,
    Cake,
    Calculator,
    CalendarCheck2,
    CalendarCheck,
    CalendarClock,
    CalendarDays,
    CalendarFold,
    CalendarHeart,
    CalendarMinus2,
    CalendarMinus,
    CalendarOff,
    CalendarPlus2,
    CalendarPlus,
    CalendarRange,
    CalendarSearch,
    CalendarX2,
    CalendarX,
    Calendar,
    CameraOff,
    Camera,
    CandlestickChart,
    CandyCane,
    CandyOff,
    Candy,
    Cannabis,
    CaptionsOff,
    Captions,
    CarFront,
    CarTaxiFront,
    Car,
    Caravan,
    Carrot,
    CaseLower,
    CaseSensitive,
    CaseUpper,
    CassetteTape,
    Cast,
    Castle,
    Cat,
    Cctv,
    CheckCheck,
    Check,
    ChefHat,
    Cherry,
    ChevronDown,
    ChevronFirst,
    ChevronLast,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    ChevronsDownUp,
    ChevronsDown,
    ChevronsLeftRight,
    ChevronsLeft,
    ChevronsRightLeft,
    ChevronsRight,
    ChevronsUpDown,
    ChevronsUp,
    Chrome,
    Church,
    CigaretteOff,
    Cigarette,
    CircleAlert,
    CircleArrowDown,
    CircleArrowLeft,
    CircleArrowOutDownLeft,
    CircleArrowOutDownRight,
    CircleArrowOutUpLeft,
    CircleArrowOutUpRight,
    CircleArrowRight,
    CircleArrowUp,
    CircleCheckBig,
    CircleCheck,
    CircleChevronDown,
    CircleChevronLeft,
    CircleChevronRight,
    CircleChevronUp,
    CircleDashed,
    CircleDivide,
    CircleDollarSign,
    CircleDotDashed,
    CircleDot,
    CircleEllipsis,
    CircleEqual,
    CircleFadingPlus,
    CircleGauge,
    CircleHelp,
    CircleMinus,
    CircleOff,
    CircleParkingOff,
    CircleParking,
    CirclePause,
    CirclePercent,
    CirclePlay,
    CirclePlus,
    CirclePower,
    CircleSlash2,
    CircleSlash,
    CircleStop,
    CircleUserRound,
    CircleUser,
    CircleX,
    Circle,
    CircuitBoard,
    Citrus,
    Clapperboard,
    ClipboardCheck,
    ClipboardCopy,
    ClipboardList,
    ClipboardMinus,
    ClipboardPaste,
    ClipboardPenLine,
    ClipboardPen,
    ClipboardPlus,
    ClipboardType,
    ClipboardX,
    Clipboard,
    Clock1,
    Clock10,
    Clock11,
    Clock12,
    Clock2,
    Clock3,
    Clock4,
    Clock5,
    Clock6,
    Clock7,
    Clock8,
    Clock9,
    Clock,
    CloudCog,
    CloudDownload,
    CloudDrizzle,
    CloudFog,
    CloudHail,
    CloudLightning,
    CloudMoonRain,
    CloudMoon,
    CloudOff,
    CloudRainWind,
    CloudRain,
    CloudSnow,
    CloudSunRain,
    CloudSun,
    CloudUpload,
    Cloud,
    Cloudy,
    Clover,
    Club,
    CodeXml,
    Code,
    Codepen,
    Codesandbox,
    Coffee,
    Cog,
    Coins,
    Columns2,
    Columns3,
    Columns4,
    Combine,
    Command,
    Compass,
    Component,
    Computer,
    ConciergeBell,
    Cone,
    Construction,
    ContactRound,
    Contact,
    Container,
    Contrast,
    Cookie,
    CookingPot,
    CopyCheck,
    CopyMinus,
    CopyPlus,
    CopySlash,
    CopyX,
    Copy,
    Copyleft,
    Copyright,
    CornerDownLeft,
    CornerDownRight,
    CornerLeftDown,
    CornerLeftUp,
    CornerRightDown,
    CornerRightUp,
    CornerUpLeft,
    CornerUpRight,
    Cpu,
    CreativeCommons,
    CreditCard,
    Croissant,
    Crop,
    Cross,
    Crosshair,
    Crown,
    Cuboid,
    CupSoda,
    Currency,
    Cylinder,
    DatabaseBackup,
    DatabaseZap,
    Database,
    Delete,
    Dessert,
    Diameter,
    DiamondPercent,
    Diamond,
    Dice1,
    Dice2,
    Dice3,
    Dice4,
    Dice5,
    Dice6,
    Dices,
    Diff,
    Disc2,
    Disc3,
    DiscAlbum,
    Disc,
    Divide,
    DnaOff,
    Dna,
    Dock,
    Dog,
    DollarSign,
    Donut,
    DoorClosed,
    DoorOpen,
    Dot,
    Download,
    DraftingCompass,
    Drama,
    Dribbble,
    Drill,
    Droplet,
    Droplets,
    Drum,
    Drumstick,
    Dumbbell,
    EarOff,
    Ear,
    EarthLock,
    Earth,
    Eclipse,
    EggFried,
    EggOff,
    Egg,
    EllipsisVertical,
    Ellipsis,
    EqualNot,
    Equal,
    Eraser,
    Euro,
    Expand,
    ExternalLink,
    EyeOff,
    Eye,
    Facebook,
    Factory,
    Fan,
    FastForward,
    Feather,
    Fence,
    FerrisWheel,
    Figma,
    FileArchive,
    FileAudio2,
    FileAudio,
    FileAxis3D,
    FileBadge2,
    FileBadge,
    FileBarChart2,
    FileBarChart,
    FileBox,
    FileCheck2,
    FileCheck,
    FileClock,
    FileCode2,
    FileCode,
    FileCog,
    FileDiff,
    FileDigit,
    FileDown,
    FileHeart,
    FileImage,
    FileInput,
    FileJson2,
    FileJson,
    FileKey2,
    FileKey,
    FileLineChart,
    FileLock2,
    FileLock,
    FileMinus2,
    FileMinus,
    FileMusic,
    FileOutput,
    FilePenLine,
    FilePen,
    FilePieChart,
    FilePlus2,
    FilePlus,
    FileQuestion,
    FileScan,
    FileSearch2,
    FileSearch,
    FileSliders,
    FileSpreadsheet,
    FileStack,
    FileSymlink,
    FileTerminal,
    FileText,
    FileType2,
    FileType,
    FileUp,
    FileVideo2,
    FileVideo,
    FileVolume2,
    FileVolume,
    FileWarning,
    FileX2,
    FileX,
    File,
    Files,
    Film,
    FilterX,
    Filter,
    Fingerprint,
    FireExtinguisher,
    FishOff,
    FishSymbol,
    Fish,
    FlagOff,
    FlagTriangleLeft,
    FlagTriangleRight,
    Flag,
    FlameKindling,
    Flame,
    FlashlightOff,
    Flashlight,
    FlaskConicalOff,
    FlaskConical,
    FlaskRound,
    FlipHorizontal2,
    FlipHorizontal,
    FlipVertical2,
    FlipVertical,
    Flower2,
    Flower,
    Focus,
    FoldHorizontal,
    FoldVertical,
    FolderArchive,
    FolderCheck,
    FolderClock,
    FolderClosed,
    FolderCog,
    FolderDot,
    FolderDown,
    FolderGit2,
    FolderGit,
    FolderHeart,
    FolderInput,
    FolderKanban,
    FolderKey,
    FolderLock,
    FolderMinus,
    FolderOpenDot,
    FolderOpen,
    FolderOutput,
    FolderPen,
    FolderPlus,
    FolderRoot,
    FolderSearch2,
    FolderSearch,
    FolderSymlink,
    FolderSync,
    FolderTree,
    FolderUp,
    FolderX,
    Folder,
    Folders,
    Footprints,
    Forklift,
    Forward,
    Frame,
    Framer,
    Frown,
    Fuel,
    Fullscreen,
    GalleryHorizontalEnd,
    GalleryHorizontal,
    GalleryThumbnails,
    GalleryVerticalEnd,
    GalleryVertical,
    Gamepad2,
    Gamepad,
    GanttChart,
    Gauge,
    Gavel,
    Gem,
    Ghost,
    Gift,
    GitBranchPlus,
    GitBranch,
    GitCommitHorizontal,
    GitCommitVertical,
    GitCompareArrows,
    GitCompare,
    GitFork,
    GitGraph,
    GitMerge,
    GitPullRequestArrow,
    GitPullRequestClosed,
    GitPullRequestCreateArrow,
    GitPullRequestCreate,
    GitPullRequestDraft,
    GitPullRequest,
    Github,
    Gitlab,
    GlassWater,
    Glasses,
    GlobeLock,
    Globe,
    Goal,
    Grab,
    GraduationCap,
    Grape,
    Grid2X2,
    Grid3X3,
    GripHorizontal,
    GripVertical,
    Grip,
    Group,
    Guitar,
    Ham,
    Hammer,
    HandCoins,
    HandHeart,
    HandHelping,
    HandMetal,
    HandPlatter,
    Hand,
    Handshake,
    HardDriveDownload,
    HardDriveUpload,
    HardDrive,
    HardHat,
    Hash,
    Haze,
    HdmiPort,
    Heading1,
    Heading2,
    Heading3,
    Heading4,
    Heading5,
    Heading6,
    Heading,
    Headphones,
    Headset,
    HeartCrack,
    HeartHandshake,
    HeartOff,
    HeartPulse,
    Heart,
    Heater,
    Hexagon,
    Highlighter,
    History,
    Home,
    HopOff,
    Hop,
    Hospital,
    Hotel,
    Hourglass,
    IceCreamBowl,
    IceCreamCone,
    ImageDown,
    ImageMinus,
    ImageOff,
    ImagePlay,
    ImagePlus,
    ImageUp,
    Image,
    Images,
    Import,
    Inbox,
    IndentDecrease,
    IndentIncrease,
    IndianRupee,
    Infinity,
    Info,
    InspectionPanel,
    Instagram,
    Italic,
    IterationCcw,
    IterationCw,
    JapaneseYen,
    Joystick,
    Kanban,
    KeyRound,
    KeySquare,
    Key,
    KeyboardMusic,
    KeyboardOff,
    Keyboard,
    LampCeiling,
    LampDesk,
    LampFloor,
    LampWallDown,
    LampWallUp,
    Lamp,
    LandPlot,
    Landmark,
    Languages,
    LaptopMinimal,
    Laptop,
    LassoSelect,
    Lasso,
    Laugh,
    Layers2,
    Layers3,
    Layers,
    LayoutDashboard,
    LayoutGrid,
    LayoutList,
    LayoutPanelLeft,
    LayoutPanelTop,
    LayoutTemplate,
    Leaf,
    LeafyGreen,
    LibraryBig,
    Library,
    LifeBuoy,
    Ligature,
    LightbulbOff,
    Lightbulb,
    LineChart,
    Link2Off,
    Link2,
    Link,
    Linkedin,
    ListChecks,
    ListCollapse,
    ListEnd,
    ListFilter,
    ListMinus,
    ListMusic,
    ListOrdered,
    ListPlus,
    ListRestart,
    ListStart,
    ListTodo,
    ListTree,
    ListVideo,
    ListX,
    List,
    LoaderCircle,
    Loader,
    LocateFixed,
    LocateOff,
    Locate,
    LockKeyholeOpen,
    LockKeyhole,
    LockOpen,
    Lock,
    LogIn,
    LogOut,
    Lollipop,
    Luggage,
    Magnet,
    MailCheck,
    MailMinus,
    MailOpen,
    MailPlus,
    MailQuestion,
    MailSearch,
    MailWarning,
    MailX,
    Mail,
    Mailbox,
    Mails,
    MapPinOff,
    MapPin,
    MapPinned,
    Map,
    Martini,
    Maximize2,
    Maximize,
    Medal,
    MegaphoneOff,
    Megaphone,
    Meh,
    MemoryStick,
    Menu,
    Merge,
    MessageCircleCode,
    MessageCircleDashed,
    MessageCircleHeart,
    MessageCircleMore,
    MessageCircleOff,
    MessageCirclePlus,
    MessageCircleQuestion,
    MessageCircleReply,
    MessageCircleWarning,
    MessageCircleX,
    MessageCircle,
    MessageSquareCode,
    MessageSquareDashed,
    MessageSquareDiff,
    MessageSquareDot,
    MessageSquareHeart,
    MessageSquareMore,
    MessageSquareOff,
    MessageSquarePlus,
    MessageSquareQuote,
    MessageSquareReply,
    MessageSquareShare,
    MessageSquareText,
    MessageSquareWarning,
    MessageSquareX,
    MessageSquare,
    MessagesSquare,
    MicOff,
    MicVocal,
    Mic,
    Microscope,
    Microwave,
    Milestone,
    MilkOff,
    Milk,
    Minimize2,
    Minimize,
    Minus,
    MonitorCheck,
    MonitorDot,
    MonitorDown,
    MonitorOff,
    MonitorPause,
    MonitorPlay,
    MonitorSmartphone,
    MonitorSpeaker,
    MonitorStop,
    MonitorUp,
    MonitorX,
    Monitor,
    MoonStar,
    Moon,
    MountainSnow,
    Mountain,
    MouseOff,
    MousePointer2,
    MousePointerClick,
    MousePointer,
    Mouse,
    Move3D,
    MoveDiagonal2,
    MoveDiagonal,
    MoveDownLeft,
    MoveDownRight,
    MoveDown,
    MoveHorizontal,
    MoveLeft,
    MoveRight,
    MoveUpLeft,
    MoveUpRight,
    MoveUp,
    MoveVertical,
    Move,
    Music2,
    Music3,
    Music4,
    Music,
    Navigation2Off,
    Navigation2,
    NavigationOff,
    Navigation,
    Network,
    Newspaper,
    Nfc,
    NotebookPen,
    NotebookTabs,
    NotebookText,
    Notebook,
    NotepadTextDashed,
    NotepadText,
    NutOff,
    Nut,
    OctagonAlert,
    OctagonPause,
    OctagonX,
    Octagon,
    Option,
    Orbit,
    Package2,
    PackageCheck,
    PackageMinus,
    PackageOpen,
    PackagePlus,
    PackageSearch,
    PackageX,
    Package,
    PaintBucket,
    PaintRoller,
    Paintbrush2,
    Paintbrush,
    Palette,
    PanelBottomClose,
    PanelBottomDashed,
    PanelBottomOpen,
    PanelBottom,
    PanelLeftClose,
    PanelLeftDashed,
    PanelLeftOpen,
    PanelLeft,
    PanelRightClose,
    PanelRightDashed,
    PanelRightOpen,
    PanelRight,
    PanelTopClose,
    PanelTopDashed,
    PanelTopOpen,
    PanelTop,
    PanelsLeftBottom,
    PanelsRightBottom,
    PanelsTopLeft,
    Paperclip,
    Parentheses,
    ParkingMeter,
    PartyPopper,
    Pause,
    PawPrint,
    PcCase,
    PenLine,
    PenTool,
    Pen,
    PencilLine,
    PencilRuler,
    Pencil,
    Pentagon,
    Percent,
    PersonStanding,
    PhoneCall,
    PhoneForwarded,
    PhoneIncoming,
    PhoneMissed,
    PhoneOff,
    PhoneOutgoing,
    Phone,
    Pi,
    Piano,
    Pickaxe,
    PictureInPicture2,
    PictureInPicture,
    PieChart,
    PiggyBank,
    PilcrowLeft,
    PilcrowRight,
    Pilcrow,
    Pill,
    PinOff,
    Pin,
    Pipette,
    Pizza,
    PlaneLanding,
    PlaneTakeoff,
    Plane,
    Play,
    Plug2,
    PlugZap2,
    PlugZap,
    Plug,
    Plus,
    PocketKnife,
    Pocket,
    Podcast,
    PointerOff,
    Pointer,
    Popcorn,
    Popsicle,
    PoundSterling,
    PowerOff,
    Power,
    Presentation,
    Printer,
    Projector,
    Proportions,
    Puzzle,
    Pyramid,
    QrCode,
    Quote,
    Rabbit,
    Radar,
    Radiation,
    Radical,
    RadioReceiver,
    RadioTower,
    Radio,
    Radius,
    RailSymbol,
    Rainbow,
    Rat,
    Ratio,
    ReceiptCent,
    ReceiptEuro,
    ReceiptIndianRupee,
    ReceiptJapaneseYen,
    ReceiptPoundSterling,
    ReceiptRussianRuble,
    ReceiptSwissFranc,
    ReceiptText,
    Receipt,
    RectangleEllipsis,
    RectangleHorizontal,
    RectangleVertical,
    Recycle,
    Redo2,
    RedoDot,
    Redo,
    RefreshCcwDot,
    RefreshCcw,
    RefreshCwOff,
    RefreshCw,
    Refrigerator,
    Regex,
    RemoveFormatting,
    Repeat1,
    Repeat2,
    Repeat,
    ReplaceAll,
    Replace,
    ReplyAll,
    Reply,
    Rewind,
    Ribbon,
    Rocket,
    RockingChair,
    RollerCoaster,
    Rotate3D,
    RotateCcwSquare,
    RotateCcw,
    RotateCwSquare,
    RotateCw,
    RouteOff,
    Route,
    Router,
    Rows2,
    Rows3,
    Rows4,
    Rss,
    Ruler,
    RussianRuble,
    Sailboat,
    Salad,
    Sandwich,
    SatelliteDish,
    Satellite,
    SaveAll,
    Save,
    Scale3D,
    Scale,
    Scaling,
    ScanBarcode,
    ScanEye,
    ScanFace,
    ScanLine,
    ScanSearch,
    ScanText,
    Scan,
    ScatterChart,
    School,
    ScissorsLineDashed,
    Scissors,
    ScreenShareOff,
    ScreenShare,
    ScrollText,
    Scroll,
    SearchCheck,
    SearchCode,
    SearchSlash,
    SearchX,
    Search,
    SendHorizontal,
    SendToBack,
    Send,
    SeparatorHorizontal,
    SeparatorVertical,
    ServerCog,
    ServerCrash,
    ServerOff,
    Server,
    Settings2,
    Settings,
    Shapes,
    Share2,
    Share,
    Sheet,
    Shell,
    ShieldAlert,
    ShieldBan,
    ShieldCheck,
    ShieldEllipsis,
    ShieldHalf,
    ShieldMinus,
    ShieldOff,
    ShieldPlus,
    ShieldQuestion,
    ShieldX,
    Shield,
    ShipWheel,
    Ship,
    Shirt,
    ShoppingBag,
    ShoppingBasket,
    ShoppingCart,
    Shovel,
    ShowerHead,
    Shrink,
    Shrub,
    Shuffle,
    Sigma,
    SignalHigh,
    SignalLow,
    SignalMedium,
    SignalZero,
    Signal,
    SignpostBig,
    Signpost,
    Siren,
    SkipBack,
    SkipForward,
    Skull,
    Slack,
    Slash,
    Slice,
    SlidersHorizontal,
    SlidersVertical,
    SmartphoneCharging,
    SmartphoneNfc,
    Smartphone,
    SmilePlus,
    Smile,
    Snail,
    Snowflake,
    Sofa,
    Soup,
    Space,
    Spade,
    Sparkle,
    Sparkles,
    Speaker,
    Speech,
    SpellCheck2,
    SpellCheck,
    Spline,
    Split,
    SprayCan,
    Sprout,
    SquareActivity,
    SquareArrowDownLeft,
    SquareArrowDownRight,
    SquareArrowDown,
    SquareArrowLeft,
    SquareArrowOutDownLeft,
    SquareArrowOutDownRight,
    SquareArrowOutUpLeft,
    SquareArrowOutUpRight,
    SquareArrowRight,
    SquareArrowUpLeft,
    SquareArrowUpRight,
    SquareArrowUp,
    SquareAsterisk,
    SquareBottomDashedScissors,
    SquareCheckBig,
    SquareCheck,
    SquareChevronDown,
    SquareChevronLeft,
    SquareChevronRight,
    SquareChevronUp,
    SquareCode,
    SquareDashedBottomCode,
    SquareDashedBottom,
    SquareDashedKanban,
    SquareDashedMousePointer,
    SquareDivide,
    SquareDot,
    SquareEqual,
    SquareFunction,
    SquareGanttChart,
    SquareKanban,
    SquareLibrary,
    SquareM,
    SquareMenu,
    SquareMinus,
    SquareMousePointer,
    SquareParkingOff,
    SquareParking,
    SquarePen,
    SquarePercent,
    SquarePi,
    SquarePilcrow,
    SquarePlay,
    SquarePlus,
    SquarePower,
    SquareRadical,
    SquareScissors,
    SquareSigma,
    SquareSlash,
    SquareSplitHorizontal,
    SquareSplitVertical,
    SquareStack,
    SquareTerminal,
    SquareUserRound,
    SquareUser,
    SquareX,
    Square,
    Squircle,
    Squirrel,
    Stamp,
    StarHalf,
    StarOff,
    Star,
    StepBack,
    StepForward,
    Stethoscope,
    Sticker,
    StickyNote,
    Store,
    StretchHorizontal,
    StretchVertical,
    Strikethrough,
    Subscript,
    SunDim,
    SunMedium,
    SunMoon,
    SunSnow,
    Sun,
    Sunrise,
    Sunset,
    Superscript,
    SwatchBook,
    SwissFranc,
    SwitchCamera,
    Sword,
    Swords,
    Syringe,
    Table2,
    TableCellsMerge,
    TableCellsSplit,
    TableColumnsSplit,
    TableProperties,
    TableRowsSplit,
    Table,
    TabletSmartphone,
    Tablet,
    Tablets,
    Tag,
    Tags,
    Tally1,
    Tally2,
    Tally3,
    Tally4,
    Tally5,
    Tangent,
    Target,
    Telescope,
    TentTree,
    Tent,
    Terminal,
    TestTubeDiagonal,
    TestTube,
    TestTubes,
    TextCursorInput,
    TextCursor,
    TextQuote,
    TextSearch,
    TextSelect,
    Text,
    Theater,
    ThermometerSnowflake,
    ThermometerSun,
    Thermometer,
    ThumbsDown,
    ThumbsUp,
    TicketCheck,
    TicketMinus,
    TicketPercent,
    TicketPlus,
    TicketSlash,
    TicketX,
    Ticket,
    TimerOff,
    TimerReset,
    Timer,
    ToggleLeft,
    ToggleRight,
    Tornado,
    Torus,
    TouchpadOff,
    Touchpad,
    TowerControl,
    ToyBrick,
    Tractor,
    TrafficCone,
    TrainFrontTunnel,
    TrainFront,
    TrainTrack,
    TramFront,
    Trash2,
    Trash,
    TreeDeciduous,
    TreePalm,
    TreePine,
    Trees,
    Trello,
    TrendingDown,
    TrendingUp,
    TriangleAlert,
    TriangleRight,
    Triangle,
    Trophy,
    Truck,
    Turtle,
    Tv2,
    Tv,
    Twitch,
    Twitter,
    Type,
    UmbrellaOff,
    Umbrella,
    Underline,
    Undo2,
    UndoDot,
    Undo,
    UnfoldHorizontal,
    UnfoldVertical,
    Ungroup,
    University,
    Unlink2,
    Unlink,
    Unplug,
    Upload,
    Usb,
    UserCheck,
    UserCog,
    UserMinus,
    UserPlus,
    UserRoundCheck,
    UserRoundCog,
    UserRoundMinus,
    UserRoundPlus,
    UserRoundSearch,
    UserRoundX,
    UserRound,
    UserSearch,
    UserX,
    User,
    UsersRound,
    Users,
    UtensilsCrossed,
    Utensils,
    UtilityPole,
    Variable,
    Vault,
    Vegan,
    VenetianMask,
    VibrateOff,
    Vibrate,
    VideoOff,
    Video,
    Videotape,
    View,
    Voicemail,
    Volume1,
    Volume2,
    VolumeX,
    Volume,
    Vote,
    WalletCards,
    WalletMinimal,
    Wallet,
    Wallpaper,
    WandSparkles,
    Wand,
    Warehouse,
    WashingMachine,
    Watch,
    Waves,
    Waypoints,
    Webcam,
    WebhookOff,
    Webhook,
    Weight,
    WheatOff,
    Wheat,
    WholeWord,
    WifiOff,
    Wifi,
    Wind,
    WineOff,
    Wine,
    Workflow,
    Worm,
    WrapText,
    Wrench,
    X,
    Youtube,
    ZapOff,
    Zap,
    ZoomIn,
    ZoomOut,
}

impl Display for Lucide {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match &self {
            Self::AArrowDown => '\u{e589}',
            Self::AArrowUp => '\u{e58a}',
            Self::ALargeSmall => '\u{e58b}',
            Self::Accessibility => '\u{e296}',
            Self::Activity => '\u{e038}',
            Self::AirVent => '\u{e350}',
            Self::Airplay => '\u{e039}',
            Self::AlarmClockCheck => '\u{e1ea}',
            Self::AlarmClockMinus => '\u{e1eb}',
            Self::AlarmClockOff => '\u{e23a}',
            Self::AlarmClockPlus => '\u{e1ec}',
            Self::AlarmClock => '\u{e03a}',
            Self::AlarmSmoke => '\u{e57f}',
            Self::Album => '\u{e03b}',
            Self::AlignCenterHorizontal => '\u{e26b}',
            Self::AlignCenterVertical => '\u{e26c}',
            Self::AlignCenter => '\u{e03c}',
            Self::AlignEndHorizontal => '\u{e26d}',
            Self::AlignEndVertical => '\u{e26e}',
            Self::AlignHorizontalDistributeCenter => '\u{e03d}',
            Self::AlignHorizontalDistributeEnd => '\u{e03e}',
            Self::AlignHorizontalDistributeStart => '\u{e03f}',
            Self::AlignHorizontalJustifyCenter => '\u{e271}',
            Self::AlignHorizontalJustifyEnd => '\u{e272}',
            Self::AlignHorizontalJustifyStart => '\u{e273}',
            Self::AlignHorizontalSpaceAround => '\u{e274}',
            Self::AlignHorizontalSpaceBetween => '\u{e275}',
            Self::AlignJustify => '\u{e040}',
            Self::AlignLeft => '\u{e041}',
            Self::AlignRight => '\u{e042}',
            Self::AlignStartHorizontal => '\u{e26f}',
            Self::AlignStartVertical => '\u{e270}',
            Self::AlignVerticalDistributeCenter => '\u{e27d}',
            Self::AlignVerticalDistributeEnd => '\u{e27e}',
            Self::AlignVerticalDistributeStart => '\u{e27f}',
            Self::AlignVerticalJustifyCenter => '\u{e276}',
            Self::AlignVerticalJustifyEnd => '\u{e277}',
            Self::AlignVerticalJustifyStart => '\u{e278}',
            Self::AlignVerticalSpaceAround => '\u{e279}',
            Self::AlignVerticalSpaceBetween => '\u{e27a}',
            Self::Ambulance => '\u{e5bf}',
            Self::Ampersand => '\u{e4a0}',
            Self::Ampersands => '\u{e4a1}',
            Self::Anchor => '\u{e043}',
            Self::Angry => '\u{e2fb}',
            Self::Annoyed => '\u{e2fc}',
            Self::Antenna => '\u{e4e6}',
            Self::Anvil => '\u{e584}',
            Self::Aperture => '\u{e044}',
            Self::AppWindowMac => '\u{e5d6}',
            Self::AppWindow => '\u{e42a}',
            Self::Apple => '\u{e351}',
            Self::ArchiveRestore => '\u{e2cc}',
            Self::ArchiveX => '\u{e510}',
            Self::Archive => '\u{e045}',
            Self::AreaChart => '\u{e4d7}',
            Self::Armchair => '\u{e2bf}',
            Self::ArrowBigDownDash => '\u{e421}',
            Self::ArrowBigDown => '\u{e1df}',
            Self::ArrowBigLeftDash => '\u{e422}',
            Self::ArrowBigLeft => '\u{e1e0}',
            Self::ArrowBigRightDash => '\u{e423}',
            Self::ArrowBigRight => '\u{e1e1}',
            Self::ArrowBigUpDash => '\u{e424}',
            Self::ArrowBigUp => '\u{e1e2}',
            Self::ArrowDown01 => '\u{e417}',
            Self::ArrowDown10 => '\u{e418}',
            Self::ArrowDownAZ => '\u{e419}',
            Self::ArrowDownFromLine => '\u{e458}',
            Self::ArrowDownLeft => '\u{e047}',
            Self::ArrowDownNarrowWide => '\u{e048}',
            Self::ArrowDownRight => '\u{e049}',
            Self::ArrowDownToDot => '\u{e451}',
            Self::ArrowDownToLine => '\u{e459}',
            Self::ArrowDownUp => '\u{e04a}',
            Self::ArrowDownWideNarrow => '\u{e04b}',
            Self::ArrowDownZA => '\u{e41a}',
            Self::ArrowDown => '\u{e046}',
            Self::ArrowLeftFromLine => '\u{e45a}',
            Self::ArrowLeftRight => '\u{e249}',
            Self::ArrowLeftToLine => '\u{e45b}',
            Self::ArrowLeft => '\u{e04c}',
            Self::ArrowRightFromLine => '\u{e45c}',
            Self::ArrowRightLeft => '\u{e41b}',
            Self::ArrowRightToLine => '\u{e45d}',
            Self::ArrowRight => '\u{e04d}',
            Self::ArrowUp01 => '\u{e41c}',
            Self::ArrowUp10 => '\u{e41d}',
            Self::ArrowUpAZ => '\u{e41e}',
            Self::ArrowUpDown => '\u{e380}',
            Self::ArrowUpFromDot => '\u{e452}',
            Self::ArrowUpFromLine => '\u{e45e}',
            Self::ArrowUpLeft => '\u{e04f}',
            Self::ArrowUpNarrowWide => '\u{e050}',
            Self::ArrowUpRight => '\u{e051}',
            Self::ArrowUpToLine => '\u{e45f}',
            Self::ArrowUpWideNarrow => '\u{e41f}',
            Self::ArrowUpZA => '\u{e420}',
            Self::ArrowUp => '\u{e04e}',
            Self::ArrowsUpFromLine => '\u{e4d8}',
            Self::Asterisk => '\u{e1ed}',
            Self::AtSign => '\u{e052}',
            Self::Atom => '\u{e3da}',
            Self::AudioLines => '\u{e55e}',
            Self::AudioWaveform => '\u{e55f}',
            Self::Award => '\u{e053}',
            Self::Axe => '\u{e054}',
            Self::Axis3D => '\u{e2fd}',
            Self::Baby => '\u{e2cd}',
            Self::Backpack => '\u{e2c7}',
            Self::BadgeAlert => '\u{e479}',
            Self::BadgeCent => '\u{e513}',
            Self::BadgeCheck => '\u{e240}',
            Self::BadgeDollarSign => '\u{e47a}',
            Self::BadgeEuro => '\u{e514}',
            Self::BadgeHelp => '\u{e47b}',
            Self::BadgeIndianRupee => '\u{e515}',
            Self::BadgeInfo => '\u{e47c}',
            Self::BadgeJapaneseYen => '\u{e516}',
            Self::BadgeMinus => '\u{e47d}',
            Self::BadgePercent => '\u{e47e}',
            Self::BadgePlus => '\u{e47f}',
            Self::BadgePoundSterling => '\u{e517}',
            Self::BadgeRussianRuble => '\u{e518}',
            Self::BadgeSwissFranc => '\u{e519}',
            Self::BadgeX => '\u{e480}',
            Self::Badge => '\u{e478}',
            Self::BaggageClaim => '\u{e2c8}',
            Self::Ban => '\u{e055}',
            Self::Banana => '\u{e352}',
            Self::Banknote => '\u{e056}',
            Self::BarChart2 => '\u{e058}',
            Self::BarChart3 => '\u{e2a1}',
            Self::BarChart4 => '\u{e2a2}',
            Self::BarChartBig => '\u{e4ab}',
            Self::BarChartHorizontalBig => '\u{e4ac}',
            Self::BarChartHorizontal => '\u{e2a3}',
            Self::BarChart => '\u{e057}',
            Self::Barcode => '\u{e537}',
            Self::Baseline => '\u{e284}',
            Self::Bath => '\u{e2aa}',
            Self::BatteryCharging => '\u{e05a}',
            Self::BatteryFull => '\u{e05b}',
            Self::BatteryLow => '\u{e05c}',
            Self::BatteryMedium => '\u{e05d}',
            Self::BatteryWarning => '\u{e3af}',
            Self::Battery => '\u{e059}',
            Self::Beaker => '\u{e05e}',
            Self::BeanOff => '\u{e393}',
            Self::Bean => '\u{e392}',
            Self::BedDouble => '\u{e2c1}',
            Self::BedSingle => '\u{e2c2}',
            Self::Bed => '\u{e2c0}',
            Self::Beef => '\u{e3a8}',
            Self::BeerOff => '\u{e5dd}',
            Self::Beer => '\u{e2ce}',
            Self::BellDot => '\u{e42f}',
            Self::BellElectric => '\u{e580}',
            Self::BellMinus => '\u{e1ee}',
            Self::BellOff => '\u{e060}',
            Self::BellPlus => '\u{e1ef}',
            Self::BellRing => '\u{e223}',
            Self::Bell => '\u{e05f}',
            Self::BetweenHorizontalEnd => '\u{e595}',
            Self::BetweenHorizontalStart => '\u{e596}',
            Self::BetweenVerticalEnd => '\u{e597}',
            Self::BetweenVerticalStart => '\u{e598}',
            Self::Bike => '\u{e1d0}',
            Self::Binary => '\u{e1f0}',
            Self::Biohazard => '\u{e445}',
            Self::Bird => '\u{e3c8}',
            Self::Bitcoin => '\u{e061}',
            Self::Blend => '\u{e5a0}',
            Self::Blinds => '\u{e3c3}',
            Self::Blocks => '\u{e4fe}',
            Self::BluetoothConnected => '\u{e1b6}',
            Self::BluetoothOff => '\u{e1b7}',
            Self::BluetoothSearching => '\u{e1b8}',
            Self::Bluetooth => '\u{e062}',
            Self::Bold => '\u{e063}',
            Self::Bolt => '\u{e590}',
            Self::Bomb => '\u{e2fe}',
            Self::Bone => '\u{e35b}',
            Self::BookA => '\u{e548}',
            Self::BookAudio => '\u{e549}',
            Self::BookCheck => '\u{e54a}',
            Self::BookCopy => '\u{e3f0}',
            Self::BookDashed => '\u{e3f1}',
            Self::BookDown => '\u{e3f2}',
            Self::BookHeadphones => '\u{e54b}',
            Self::BookHeart => '\u{e54c}',
            Self::BookImage => '\u{e54d}',
            Self::BookKey => '\u{e3f3}',
            Self::BookLock => '\u{e3f4}',
            Self::BookMarked => '\u{e3f5}',
            Self::BookMinus => '\u{e3f6}',
            Self::BookOpenCheck => '\u{e384}',
            Self::BookOpenText => '\u{e54e}',
            Self::BookOpen => '\u{e065}',
            Self::BookPlus => '\u{e3f7}',
            Self::BookText => '\u{e54f}',
            Self::BookType => '\u{e550}',
            Self::BookUp2 => '\u{e4aa}',
            Self::BookUp => '\u{e3f8}',
            Self::BookUser => '\u{e551}',
            Self::BookX => '\u{e3f9}',
            Self::Book => '\u{e064}',
            Self::BookmarkCheck => '\u{e523}',
            Self::BookmarkMinus => '\u{e23b}',
            Self::BookmarkPlus => '\u{e23c}',
            Self::BookmarkX => '\u{e524}',
            Self::Bookmark => '\u{e066}',
            Self::BoomBox => '\u{e4f2}',
            Self::BotMessageSquare => '\u{e5d2}',
            Self::Bot => '\u{e1b9}',
            Self::BoxSelect => '\u{e1ba}',
            Self::Box => '\u{e067}',
            Self::Boxes => '\u{e2cf}',
            Self::Braces => '\u{e36d}',
            Self::Brackets => '\u{e447}',
            Self::BrainCircuit => '\u{e3ca}',
            Self::BrainCog => '\u{e3cb}',
            Self::Brain => '\u{e3c9}',
            Self::BrickWall => '\u{e585}',
            Self::BriefcaseBusiness => '\u{e5d9}',
            Self::BriefcaseMedical => '\u{e5da}',
            Self::Briefcase => '\u{e068}',
            Self::BringToFront => '\u{e4f3}',
            Self::Brush => '\u{e1d1}',
            Self::BugOff => '\u{e511}',
            Self::BugPlay => '\u{e512}',
            Self::Bug => '\u{e20a}',
            Self::Building2 => '\u{e28f}',
            Self::Building => '\u{e1ca}',
            Self::BusFront => '\u{e4ff}',
            Self::Bus => '\u{e1d2}',
            Self::CableCar => '\u{e500}',
            Self::Cable => '\u{e4e7}',
            Self::CakeSlice => '\u{e4bd}',
            Self::Cake => '\u{e347}',
            Self::Calculator => '\u{e1bb}',
            Self::CalendarCheck2 => '\u{e2b7}',
            Self::CalendarCheck => '\u{e2b6}',
            Self::CalendarClock => '\u{e303}',
            Self::CalendarDays => '\u{e2b8}',
            Self::CalendarFold => '\u{e5b8}',
            Self::CalendarHeart => '\u{e304}',
            Self::CalendarMinus2 => '\u{e5b9}',
            Self::CalendarMinus => '\u{e2b9}',
            Self::CalendarOff => '\u{e2ba}',
            Self::CalendarPlus2 => '\u{e5ba}',
            Self::CalendarPlus => '\u{e2bb}',
            Self::CalendarRange => '\u{e2bc}',
            Self::CalendarSearch => '\u{e305}',
            Self::CalendarX2 => '\u{e2be}',
            Self::CalendarX => '\u{e2bd}',
            Self::Calendar => '\u{e069}',
            Self::CameraOff => '\u{e06b}',
            Self::Camera => '\u{e06a}',
            Self::CandlestickChart => '\u{e4ad}',
            Self::CandyCane => '\u{e4be}',
            Self::CandyOff => '\u{e395}',
            Self::Candy => '\u{e394}',
            Self::Cannabis => '\u{e5d8}',
            Self::CaptionsOff => '\u{e5c5}',
            Self::Captions => '\u{e3a7}',
            Self::CarFront => '\u{e501}',
            Self::CarTaxiFront => '\u{e502}',
            Self::Car => '\u{e1d3}',
            Self::Caravan => '\u{e53d}',
            Self::Carrot => '\u{e259}',
            Self::CaseLower => '\u{e3db}',
            Self::CaseSensitive => '\u{e3dc}',
            Self::CaseUpper => '\u{e3dd}',
            Self::CassetteTape => '\u{e4ce}',
            Self::Cast => '\u{e06c}',
            Self::Castle => '\u{e3e3}',
            Self::Cat => '\u{e38f}',
            Self::Cctv => '\u{e581}',
            Self::CheckCheck => '\u{e391}',
            Self::Check => '\u{e06d}',
            Self::ChefHat => '\u{e2ab}',
            Self::Cherry => '\u{e353}',
            Self::ChevronDown => '\u{e06e}',
            Self::ChevronFirst => '\u{e242}',
            Self::ChevronLast => '\u{e243}',
            Self::ChevronLeft => '\u{e06f}',
            Self::ChevronRight => '\u{e070}',
            Self::ChevronUp => '\u{e071}',
            Self::ChevronsDownUp => '\u{e227}',
            Self::ChevronsDown => '\u{e072}',
            Self::ChevronsLeftRight => '\u{e292}',
            Self::ChevronsLeft => '\u{e073}',
            Self::ChevronsRightLeft => '\u{e293}',
            Self::ChevronsRight => '\u{e074}',
            Self::ChevronsUpDown => '\u{e210}',
            Self::ChevronsUp => '\u{e075}',
            Self::Chrome => '\u{e076}',
            Self::Church => '\u{e3e4}',
            Self::CigaretteOff => '\u{e2c6}',
            Self::Cigarette => '\u{e2c5}',
            Self::CircleAlert => '\u{e078}',
            Self::CircleArrowDown => '\u{e079}',
            Self::CircleArrowLeft => '\u{e07a}',
            Self::CircleArrowOutDownLeft => '\u{e3fb}',
            Self::CircleArrowOutDownRight => '\u{e3fc}',
            Self::CircleArrowOutUpLeft => '\u{e3fd}',
            Self::CircleArrowOutUpRight => '\u{e3fe}',
            Self::CircleArrowRight => '\u{e07b}',
            Self::CircleArrowUp => '\u{e07c}',
            Self::CircleCheckBig => '\u{e07d}',
            Self::CircleCheck => '\u{e225}',
            Self::CircleChevronDown => '\u{e4e1}',
            Self::CircleChevronLeft => '\u{e4e2}',
            Self::CircleChevronRight => '\u{e4e3}',
            Self::CircleChevronUp => '\u{e4e4}',
            Self::CircleDashed => '\u{e4b4}',
            Self::CircleDivide => '\u{e07e}',
            Self::CircleDollarSign => '\u{e481}',
            Self::CircleDotDashed => '\u{e4b5}',
            Self::CircleDot => '\u{e348}',
            Self::CircleEllipsis => '\u{e349}',
            Self::CircleEqual => '\u{e404}',
            Self::CircleFadingPlus => '\u{e5c0}',
            Self::CircleGauge => '\u{e4e5}',
            Self::CircleHelp => '\u{e07f}',
            Self::CircleMinus => '\u{e080}',
            Self::CircleOff => '\u{e405}',
            Self::CircleParkingOff => '\u{e3cd}',
            Self::CircleParking => '\u{e3cc}',
            Self::CirclePause => '\u{e081}',
            Self::CirclePercent => '\u{e51e}',
            Self::CirclePlay => '\u{e082}',
            Self::CirclePlus => '\u{e083}',
            Self::CirclePower => '\u{e554}',
            Self::CircleSlash2 => '\u{e212}',
            Self::CircleSlash => '\u{e406}',
            Self::CircleStop => '\u{e084}',
            Self::CircleUserRound => '\u{e466}',
            Self::CircleUser => '\u{e465}',
            Self::CircleX => '\u{e085}',
            Self::Circle => '\u{e077}',
            Self::CircuitBoard => '\u{e407}',
            Self::Citrus => '\u{e378}',
            Self::Clapperboard => '\u{e29a}',
            Self::ClipboardCheck => '\u{e218}',
            Self::ClipboardCopy => '\u{e224}',
            Self::ClipboardList => '\u{e087}',
            Self::ClipboardMinus => '\u{e5c2}',
            Self::ClipboardPaste => '\u{e3eb}',
            Self::ClipboardPenLine => '\u{e307}',
            Self::ClipboardPen => '\u{e306}',
            Self::ClipboardPlus => '\u{e5c3}',
            Self::ClipboardType => '\u{e308}',
            Self::ClipboardX => '\u{e221}',
            Self::Clipboard => '\u{e086}',
            Self::Clock1 => '\u{e24a}',
            Self::Clock10 => '\u{e24b}',
            Self::Clock11 => '\u{e24c}',
            Self::Clock12 => '\u{e24d}',
            Self::Clock2 => '\u{e24e}',
            Self::Clock3 => '\u{e24f}',
            Self::Clock4 => '\u{e250}',
            Self::Clock5 => '\u{e251}',
            Self::Clock6 => '\u{e252}',
            Self::Clock7 => '\u{e253}',
            Self::Clock8 => '\u{e254}',
            Self::Clock9 => '\u{e255}',
            Self::Clock => '\u{e088}',
            Self::CloudCog => '\u{e309}',
            Self::CloudDownload => '\u{e08a}',
            Self::CloudDrizzle => '\u{e08b}',
            Self::CloudFog => '\u{e213}',
            Self::CloudHail => '\u{e08c}',
            Self::CloudLightning => '\u{e08d}',
            Self::CloudMoonRain => '\u{e2f9}',
            Self::CloudMoon => '\u{e214}',
            Self::CloudOff => '\u{e08e}',
            Self::CloudRainWind => '\u{e090}',
            Self::CloudRain => '\u{e08f}',
            Self::CloudSnow => '\u{e091}',
            Self::CloudSunRain => '\u{e2fa}',
            Self::CloudSun => '\u{e215}',
            Self::CloudUpload => '\u{e092}',
            Self::Cloud => '\u{e089}',
            Self::Cloudy => '\u{e216}',
            Self::Clover => '\u{e093}',
            Self::Club => '\u{e49a}',
            Self::CodeXml => '\u{e204}',
            Self::Code => '\u{e094}',
            Self::Codepen => '\u{e095}',
            Self::Codesandbox => '\u{e096}',
            Self::Coffee => '\u{e097}',
            Self::Cog => '\u{e30a}',
            Self::Coins => '\u{e098}',
            Self::Columns2 => '\u{e099}',
            Self::Columns3 => '\u{e09a}',
            Self::Columns4 => '\u{e58d}',
            Self::Combine => '\u{e450}',
            Self::Command => '\u{e09b}',
            Self::Compass => '\u{e09c}',
            Self::Component => '\u{e2ac}',
            Self::Computer => '\u{e4e8}',
            Self::ConciergeBell => '\u{e37b}',
            Self::Cone => '\u{e527}',
            Self::Construction => '\u{e3b7}',
            Self::ContactRound => '\u{e467}',
            Self::Contact => '\u{e09d}',
            Self::Container => '\u{e4d9}',
            Self::Contrast => '\u{e09e}',
            Self::Cookie => '\u{e26a}',
            Self::CookingPot => '\u{e588}',
            Self::CopyCheck => '\u{e3ff}',
            Self::CopyMinus => '\u{e400}',
            Self::CopyPlus => '\u{e401}',
            Self::CopySlash => '\u{e402}',
            Self::CopyX => '\u{e403}',
            Self::Copy => '\u{e09f}',
            Self::Copyleft => '\u{e0a0}',
            Self::Copyright => '\u{e0a1}',
            Self::CornerDownLeft => '\u{e0a2}',
            Self::CornerDownRight => '\u{e0a3}',
            Self::CornerLeftDown => '\u{e0a4}',
            Self::CornerLeftUp => '\u{e0a5}',
            Self::CornerRightDown => '\u{e0a6}',
            Self::CornerRightUp => '\u{e0a7}',
            Self::CornerUpLeft => '\u{e0a8}',
            Self::CornerUpRight => '\u{e0a9}',
            Self::Cpu => '\u{e0aa}',
            Self::CreativeCommons => '\u{e3b5}',
            Self::CreditCard => '\u{e0ab}',
            Self::Croissant => '\u{e2ad}',
            Self::Crop => '\u{e0ac}',
            Self::Cross => '\u{e1e3}',
            Self::Crosshair => '\u{e0ad}',
            Self::Crown => '\u{e1d4}',
            Self::Cuboid => '\u{e528}',
            Self::CupSoda => '\u{e2d0}',
            Self::Currency => '\u{e22f}',
            Self::Cylinder => '\u{e529}',
            Self::DatabaseBackup => '\u{e3ae}',
            Self::DatabaseZap => '\u{e50f}',
            Self::Database => '\u{e0ae}',
            Self::Delete => '\u{e0af}',
            Self::Dessert => '\u{e4bf}',
            Self::Diameter => '\u{e52a}',
            Self::DiamondPercent => '\u{e51f}',
            Self::Diamond => '\u{e2d1}',
            Self::Dice1 => '\u{e286}',
            Self::Dice2 => '\u{e287}',
            Self::Dice3 => '\u{e288}',
            Self::Dice4 => '\u{e289}',
            Self::Dice5 => '\u{e28a}',
            Self::Dice6 => '\u{e28b}',
            Self::Dices => '\u{e2c4}',
            Self::Diff => '\u{e30b}',
            Self::Disc2 => '\u{e3fa}',
            Self::Disc3 => '\u{e498}',
            Self::DiscAlbum => '\u{e560}',
            Self::Disc => '\u{e0b0}',
            Self::Divide => '\u{e0b1}',
            Self::DnaOff => '\u{e397}',
            Self::Dna => '\u{e396}',
            Self::Dock => '\u{e5d7}',
            Self::Dog => '\u{e390}',
            Self::DollarSign => '\u{e0b2}',
            Self::Donut => '\u{e4c0}',
            Self::DoorClosed => '\u{e3d8}',
            Self::DoorOpen => '\u{e3d9}',
            Self::Dot => '\u{e453}',
            Self::Download => '\u{e0b3}',
            Self::DraftingCompass => '\u{e52b}',
            Self::Drama => '\u{e525}',
            Self::Dribbble => '\u{e0b4}',
            Self::Drill => '\u{e591}',
            Self::Droplet => '\u{e0b5}',
            Self::Droplets => '\u{e0b6}',
            Self::Drum => '\u{e561}',
            Self::Drumstick => '\u{e25a}',
            Self::Dumbbell => '\u{e3a4}',
            Self::EarOff => '\u{e386}',
            Self::Ear => '\u{e385}',
            Self::EarthLock => '\u{e5d0}',
            Self::Earth => '\u{e1f1}',
            Self::Eclipse => '\u{e5a1}',
            Self::EggFried => '\u{e354}',
            Self::EggOff => '\u{e398}',
            Self::Egg => '\u{e25c}',
            Self::EllipsisVertical => '\u{e0b8}',
            Self::Ellipsis => '\u{e0b7}',
            Self::EqualNot => '\u{e1bd}',
            Self::Equal => '\u{e1bc}',
            Self::Eraser => '\u{e28e}',
            Self::Euro => '\u{e0b9}',
            Self::Expand => '\u{e219}',
            Self::ExternalLink => '\u{e0ba}',
            Self::EyeOff => '\u{e0bc}',
            Self::Eye => '\u{e0bb}',
            Self::Facebook => '\u{e0bd}',
            Self::Factory => '\u{e29e}',
            Self::Fan => '\u{e37c}',
            Self::FastForward => '\u{e0be}',
            Self::Feather => '\u{e0bf}',
            Self::Fence => '\u{e586}',
            Self::FerrisWheel => '\u{e483}',
            Self::Figma => '\u{e0c0}',
            Self::FileArchive => '\u{e30c}',
            Self::FileAudio2 => '\u{e30e}',
            Self::FileAudio => '\u{e30d}',
            Self::FileAxis3D => '\u{e30f}',
            Self::FileBadge2 => '\u{e311}',
            Self::FileBadge => '\u{e310}',
            Self::FileBarChart2 => '\u{e313}',
            Self::FileBarChart => '\u{e312}',
            Self::FileBox => '\u{e314}',
            Self::FileCheck2 => '\u{e0c3}',
            Self::FileCheck => '\u{e0c2}',
            Self::FileClock => '\u{e315}',
            Self::FileCode2 => '\u{e462}',
            Self::FileCode => '\u{e0c4}',
            Self::FileCog => '\u{e316}',
            Self::FileDiff => '\u{e317}',
            Self::FileDigit => '\u{e0c5}',
            Self::FileDown => '\u{e318}',
            Self::FileHeart => '\u{e319}',
            Self::FileImage => '\u{e31a}',
            Self::FileInput => '\u{e0c6}',
            Self::FileJson2 => '\u{e36f}',
            Self::FileJson => '\u{e36e}',
            Self::FileKey2 => '\u{e31c}',
            Self::FileKey => '\u{e31b}',
            Self::FileLineChart => '\u{e31d}',
            Self::FileLock2 => '\u{e31f}',
            Self::FileLock => '\u{e31e}',
            Self::FileMinus2 => '\u{e0c8}',
            Self::FileMinus => '\u{e0c7}',
            Self::FileMusic => '\u{e562}',
            Self::FileOutput => '\u{e0c9}',
            Self::FilePenLine => '\u{e321}',
            Self::FilePen => '\u{e320}',
            Self::FilePieChart => '\u{e322}',
            Self::FilePlus2 => '\u{e0cb}',
            Self::FilePlus => '\u{e0ca}',
            Self::FileQuestion => '\u{e323}',
            Self::FileScan => '\u{e324}',
            Self::FileSearch2 => '\u{e325}',
            Self::FileSearch => '\u{e0cc}',
            Self::FileSliders => '\u{e5a4}',
            Self::FileSpreadsheet => '\u{e326}',
            Self::FileStack => '\u{e4a5}',
            Self::FileSymlink => '\u{e327}',
            Self::FileTerminal => '\u{e328}',
            Self::FileText => '\u{e0cd}',
            Self::FileType2 => '\u{e370}',
            Self::FileType => '\u{e329}',
            Self::FileUp => '\u{e32a}',
            Self::FileVideo2 => '\u{e32c}',
            Self::FileVideo => '\u{e32b}',
            Self::FileVolume2 => '\u{e32e}',
            Self::FileVolume => '\u{e32d}',
            Self::FileWarning => '\u{e32f}',
            Self::FileX2 => '\u{e0cf}',
            Self::FileX => '\u{e0ce}',
            Self::File => '\u{e0c1}',
            Self::Files => '\u{e0d0}',
            Self::Film => '\u{e0d1}',
            Self::FilterX => '\u{e3b8}',
            Self::Filter => '\u{e0d2}',
            Self::Fingerprint => '\u{e2ca}',
            Self::FireExtinguisher => '\u{e582}',
            Self::FishOff => '\u{e3b3}',
            Self::FishSymbol => '\u{e4f8}',
            Self::Fish => '\u{e3a9}',
            Self::FlagOff => '\u{e291}',
            Self::FlagTriangleLeft => '\u{e236}',
            Self::FlagTriangleRight => '\u{e237}',
            Self::Flag => '\u{e0d3}',
            Self::FlameKindling => '\u{e53e}',
            Self::Flame => '\u{e0d4}',
            Self::FlashlightOff => '\u{e0d6}',
            Self::Flashlight => '\u{e0d5}',
            Self::FlaskConicalOff => '\u{e399}',
            Self::FlaskConical => '\u{e0d7}',
            Self::FlaskRound => '\u{e0d8}',
            Self::FlipHorizontal2 => '\u{e361}',
            Self::FlipHorizontal => '\u{e360}',
            Self::FlipVertical2 => '\u{e363}',
            Self::FlipVertical => '\u{e362}',
            Self::Flower2 => '\u{e2d3}',
            Self::Flower => '\u{e2d2}',
            Self::Focus => '\u{e29d}',
            Self::FoldHorizontal => '\u{e43f}',
            Self::FoldVertical => '\u{e440}',
            Self::FolderArchive => '\u{e330}',
            Self::FolderCheck => '\u{e331}',
            Self::FolderClock => '\u{e332}',
            Self::FolderClosed => '\u{e333}',
            Self::FolderCog => '\u{e334}',
            Self::FolderDot => '\u{e4c8}',
            Self::FolderDown => '\u{e335}',
            Self::FolderGit2 => '\u{e40e}',
            Self::FolderGit => '\u{e40d}',
            Self::FolderHeart => '\u{e336}',
            Self::FolderInput => '\u{e337}',
            Self::FolderKanban => '\u{e4c9}',
            Self::FolderKey => '\u{e338}',
            Self::FolderLock => '\u{e339}',
            Self::FolderMinus => '\u{e0da}',
            Self::FolderOpenDot => '\u{e4ca}',
            Self::FolderOpen => '\u{e246}',
            Self::FolderOutput => '\u{e33a}',
            Self::FolderPen => '\u{e33b}',
            Self::FolderPlus => '\u{e0db}',
            Self::FolderRoot => '\u{e4cb}',
            Self::FolderSearch2 => '\u{e33d}',
            Self::FolderSearch => '\u{e33c}',
            Self::FolderSymlink => '\u{e33e}',
            Self::FolderSync => '\u{e4cc}',
            Self::FolderTree => '\u{e33f}',
            Self::FolderUp => '\u{e340}',
            Self::FolderX => '\u{e341}',
            Self::Folder => '\u{e0d9}',
            Self::Folders => '\u{e342}',
            Self::Footprints => '\u{e3bc}',
            Self::Forklift => '\u{e3c4}',
            Self::Forward => '\u{e228}',
            Self::Frame => '\u{e290}',
            Self::Framer => '\u{e0dc}',
            Self::Frown => '\u{e0dd}',
            Self::Fuel => '\u{e2ae}',
            Self::Fullscreen => '\u{e538}',
            Self::GalleryHorizontalEnd => '\u{e4d3}',
            Self::GalleryHorizontal => '\u{e4d2}',
            Self::GalleryThumbnails => '\u{e4d4}',
            Self::GalleryVerticalEnd => '\u{e4d6}',
            Self::GalleryVertical => '\u{e4d5}',
            Self::Gamepad2 => '\u{e0df}',
            Self::Gamepad => '\u{e0de}',
            Self::GanttChart => '\u{e4cd}',
            Self::Gauge => '\u{e1be}',
            Self::Gavel => '\u{e0e0}',
            Self::Gem => '\u{e241}',
            Self::Ghost => '\u{e20c}',
            Self::Gift => '\u{e0e1}',
            Self::GitBranchPlus => '\u{e1f2}',
            Self::GitBranch => '\u{e0e2}',
            Self::GitCommitHorizontal => '\u{e0e3}',
            Self::GitCommitVertical => '\u{e556}',
            Self::GitCompareArrows => '\u{e557}',
            Self::GitCompare => '\u{e35c}',
            Self::GitFork => '\u{e28c}',
            Self::GitGraph => '\u{e558}',
            Self::GitMerge => '\u{e0e4}',
            Self::GitPullRequestArrow => '\u{e559}',
            Self::GitPullRequestClosed => '\u{e35d}',
            Self::GitPullRequestCreateArrow => '\u{e55b}',
            Self::GitPullRequestCreate => '\u{e55a}',
            Self::GitPullRequestDraft => '\u{e35e}',
            Self::GitPullRequest => '\u{e0e5}',
            Self::Github => '\u{e0e6}',
            Self::Gitlab => '\u{e0e7}',
            Self::GlassWater => '\u{e2d4}',
            Self::Glasses => '\u{e20b}',
            Self::GlobeLock => '\u{e5d1}',
            Self::Globe => '\u{e0e8}',
            Self::Goal => '\u{e4a9}',
            Self::Grab => '\u{e1e4}',
            Self::GraduationCap => '\u{e233}',
            Self::Grape => '\u{e355}',
            Self::Grid2X2 => '\u{e503}',
            Self::Grid3X3 => '\u{e0e9}',
            Self::GripHorizontal => '\u{e0ea}',
            Self::GripVertical => '\u{e0eb}',
            Self::Grip => '\u{e3b4}',
            Self::Group => '\u{e468}',
            Self::Guitar => '\u{e563}',
            Self::Ham => '\u{e5db}',
            Self::Hammer => '\u{e0ec}',
            Self::HandCoins => '\u{e5bc}',
            Self::HandHeart => '\u{e5bd}',
            Self::HandHelping => '\u{e3bb}',
            Self::HandMetal => '\u{e22b}',
            Self::HandPlatter => '\u{e5be}',
            Self::Hand => '\u{e1d5}',
            Self::Handshake => '\u{e5c4}',
            Self::HardDriveDownload => '\u{e4e9}',
            Self::HardDriveUpload => '\u{e4ea}',
            Self::HardDrive => '\u{e0ed}',
            Self::HardHat => '\u{e0ee}',
            Self::Hash => '\u{e0ef}',
            Self::Haze => '\u{e0f0}',
            Self::HdmiPort => '\u{e4eb}',
            Self::Heading1 => '\u{e388}',
            Self::Heading2 => '\u{e389}',
            Self::Heading3 => '\u{e38a}',
            Self::Heading4 => '\u{e38b}',
            Self::Heading5 => '\u{e38c}',
            Self::Heading6 => '\u{e38d}',
            Self::Heading => '\u{e387}',
            Self::Headphones => '\u{e0f1}',
            Self::Headset => '\u{e5c1}',
            Self::HeartCrack => '\u{e2d5}',
            Self::HeartHandshake => '\u{e2d6}',
            Self::HeartOff => '\u{e294}',
            Self::HeartPulse => '\u{e371}',
            Self::Heart => '\u{e0f2}',
            Self::Heater => '\u{e592}',
            Self::Hexagon => '\u{e0f3}',
            Self::Highlighter => '\u{e0f4}',
            Self::History => '\u{e1f3}',
            Self::Home => '\u{e0f5}',
            Self::HopOff => '\u{e39b}',
            Self::Hop => '\u{e39a}',
            Self::Hospital => '\u{e5dc}',
            Self::Hotel => '\u{e3e5}',
            Self::Hourglass => '\u{e295}',
            Self::IceCreamBowl => '\u{e3aa}',
            Self::IceCreamCone => '\u{e356}',
            Self::ImageDown => '\u{e540}',
            Self::ImageMinus => '\u{e1f4}',
            Self::ImageOff => '\u{e1bf}',
            Self::ImagePlay => '\u{e5e3}',
            Self::ImagePlus => '\u{e1f5}',
            Self::ImageUp => '\u{e5cf}',
            Self::Image => '\u{e0f6}',
            Self::Images => '\u{e5c8}',
            Self::Import => '\u{e22e}',
            Self::Inbox => '\u{e0f7}',
            Self::IndentDecrease => '\u{e0f8}',
            Self::IndentIncrease => '\u{e0f9}',
            Self::IndianRupee => '\u{e0fa}',
            Self::Infinity => '\u{e1e5}',
            Self::Info => '\u{e0fb}',
            Self::InspectionPanel => '\u{e587}',
            Self::Instagram => '\u{e0fc}',
            Self::Italic => '\u{e0fd}',
            Self::IterationCcw => '\u{e427}',
            Self::IterationCw => '\u{e428}',
            Self::JapaneseYen => '\u{e0fe}',
            Self::Joystick => '\u{e358}',
            Self::Kanban => '\u{e4e0}',
            Self::KeyRound => '\u{e4a7}',
            Self::KeySquare => '\u{e4a8}',
            Self::Key => '\u{e0ff}',
            Self::KeyboardMusic => '\u{e564}',
            Self::KeyboardOff => '\u{e5e2}',
            Self::Keyboard => '\u{e283}',
            Self::LampCeiling => '\u{e2d8}',
            Self::LampDesk => '\u{e2d9}',
            Self::LampFloor => '\u{e2da}',
            Self::LampWallDown => '\u{e2db}',
            Self::LampWallUp => '\u{e2dc}',
            Self::Lamp => '\u{e2d7}',
            Self::LandPlot => '\u{e52c}',
            Self::Landmark => '\u{e239}',
            Self::Languages => '\u{e100}',
            Self::LaptopMinimal => '\u{e1d6}',
            Self::Laptop => '\u{e1cb}',
            Self::LassoSelect => '\u{e1cd}',
            Self::Lasso => '\u{e1cc}',
            Self::Laugh => '\u{e2ff}',
            Self::Layers2 => '\u{e52d}',
            Self::Layers3 => '\u{e52e}',
            Self::Layers => '\u{e101}',
            Self::LayoutDashboard => '\u{e1c0}',
            Self::LayoutGrid => '\u{e102}',
            Self::LayoutList => '\u{e1d7}',
            Self::LayoutPanelLeft => '\u{e474}',
            Self::LayoutPanelTop => '\u{e475}',
            Self::LayoutTemplate => '\u{e205}',
            Self::Leaf => '\u{e2dd}',
            Self::LeafyGreen => '\u{e473}',
            Self::LibraryBig => '\u{e552}',
            Self::Library => '\u{e103}',
            Self::LifeBuoy => '\u{e104}',
            Self::Ligature => '\u{e43e}',
            Self::LightbulbOff => '\u{e206}',
            Self::Lightbulb => '\u{e1c1}',
            Self::LineChart => '\u{e2a4}',
            Self::Link2Off => '\u{e107}',
            Self::Link2 => '\u{e106}',
            Self::Link => '\u{e105}',
            Self::Linkedin => '\u{e108}',
            Self::ListChecks => '\u{e1ce}',
            Self::ListCollapse => '\u{e59f}',
            Self::ListEnd => '\u{e2de}',
            Self::ListFilter => '\u{e464}',
            Self::ListMinus => '\u{e23d}',
            Self::ListMusic => '\u{e2df}',
            Self::ListOrdered => '\u{e1cf}',
            Self::ListPlus => '\u{e23e}',
            Self::ListRestart => '\u{e456}',
            Self::ListStart => '\u{e2e0}',
            Self::ListTodo => '\u{e4c7}',
            Self::ListTree => '\u{e40c}',
            Self::ListVideo => '\u{e2e1}',
            Self::ListX => '\u{e23f}',
            Self::List => '\u{e109}',
            Self::LoaderCircle => '\u{e10b}',
            Self::Loader => '\u{e10a}',
            Self::LocateFixed => '\u{e1d9}',
            Self::LocateOff => '\u{e281}',
            Self::Locate => '\u{e1d8}',
            Self::LockKeyholeOpen => '\u{e536}',
            Self::LockKeyhole => '\u{e535}',
            Self::LockOpen => '\u{e10d}',
            Self::Lock => '\u{e10c}',
            Self::LogIn => '\u{e10e}',
            Self::LogOut => '\u{e10f}',
            Self::Lollipop => '\u{e4c1}',
            Self::Luggage => '\u{e2c9}',
            Self::Magnet => '\u{e2b4}',
            Self::MailCheck => '\u{e364}',
            Self::MailMinus => '\u{e365}',
            Self::MailOpen => '\u{e366}',
            Self::MailPlus => '\u{e367}',
            Self::MailQuestion => '\u{e368}',
            Self::MailSearch => '\u{e369}',
            Self::MailWarning => '\u{e36a}',
            Self::MailX => '\u{e36b}',
            Self::Mail => '\u{e110}',
            Self::Mailbox => '\u{e3d7}',
            Self::Mails => '\u{e36c}',
            Self::MapPinOff => '\u{e2a5}',
            Self::MapPin => '\u{e112}',
            Self::MapPinned => '\u{e541}',
            Self::Map => '\u{e111}',
            Self::Martini => '\u{e2e2}',
            Self::Maximize2 => '\u{e114}',
            Self::Maximize => '\u{e113}',
            Self::Medal => '\u{e372}',
            Self::MegaphoneOff => '\u{e373}',
            Self::Megaphone => '\u{e234}',
            Self::Meh => '\u{e115}',
            Self::MemoryStick => '\u{e449}',
            Self::Menu => '\u{e116}',
            Self::Merge => '\u{e443}',
            Self::MessageCircleCode => '\u{e566}',
            Self::MessageCircleDashed => '\u{e567}',
            Self::MessageCircleHeart => '\u{e568}',
            Self::MessageCircleMore => '\u{e569}',
            Self::MessageCircleOff => '\u{e56a}',
            Self::MessageCirclePlus => '\u{e56b}',
            Self::MessageCircleQuestion => '\u{e56c}',
            Self::MessageCircleReply => '\u{e56d}',
            Self::MessageCircleWarning => '\u{e56e}',
            Self::MessageCircleX => '\u{e56f}',
            Self::MessageCircle => '\u{e117}',
            Self::MessageSquareCode => '\u{e570}',
            Self::MessageSquareDashed => '\u{e40f}',
            Self::MessageSquareDiff => '\u{e571}',
            Self::MessageSquareDot => '\u{e572}',
            Self::MessageSquareHeart => '\u{e573}',
            Self::MessageSquareMore => '\u{e574}',
            Self::MessageSquareOff => '\u{e575}',
            Self::MessageSquarePlus => '\u{e410}',
            Self::MessageSquareQuote => '\u{e576}',
            Self::MessageSquareReply => '\u{e577}',
            Self::MessageSquareShare => '\u{e578}',
            Self::MessageSquareText => '\u{e579}',
            Self::MessageSquareWarning => '\u{e57a}',
            Self::MessageSquareX => '\u{e57b}',
            Self::MessageSquare => '\u{e118}',
            Self::MessagesSquare => '\u{e411}',
            Self::MicOff => '\u{e11a}',
            Self::MicVocal => '\u{e34c}',
            Self::Mic => '\u{e119}',
            Self::Microscope => '\u{e2e3}',
            Self::Microwave => '\u{e37d}',
            Self::Milestone => '\u{e297}',
            Self::MilkOff => '\u{e39d}',
            Self::Milk => '\u{e39c}',
            Self::Minimize2 => '\u{e11c}',
            Self::Minimize => '\u{e11b}',
            Self::Minus => '\u{e11d}',
            Self::MonitorCheck => '\u{e486}',
            Self::MonitorDot => '\u{e487}',
            Self::MonitorDown => '\u{e425}',
            Self::MonitorOff => '\u{e1da}',
            Self::MonitorPause => '\u{e488}',
            Self::MonitorPlay => '\u{e489}',
            Self::MonitorSmartphone => '\u{e3a5}',
            Self::MonitorSpeaker => '\u{e20e}',
            Self::MonitorStop => '\u{e48a}',
            Self::MonitorUp => '\u{e426}',
            Self::MonitorX => '\u{e48b}',
            Self::Monitor => '\u{e11e}',
            Self::MoonStar => '\u{e414}',
            Self::Moon => '\u{e11f}',
            Self::MountainSnow => '\u{e231}',
            Self::Mountain => '\u{e230}',
            Self::MouseOff => '\u{e5df}',
            Self::MousePointer2 => '\u{e1c2}',
            Self::MousePointerClick => '\u{e121}',
            Self::MousePointer => '\u{e120}',
            Self::Mouse => '\u{e28d}',
            Self::Move3D => '\u{e2e4}',
            Self::MoveDiagonal2 => '\u{e1c4}',
            Self::MoveDiagonal => '\u{e1c3}',
            Self::MoveDownLeft => '\u{e491}',
            Self::MoveDownRight => '\u{e492}',
            Self::MoveDown => '\u{e490}',
            Self::MoveHorizontal => '\u{e1c5}',
            Self::MoveLeft => '\u{e493}',
            Self::MoveRight => '\u{e494}',
            Self::MoveUpLeft => '\u{e496}',
            Self::MoveUpRight => '\u{e497}',
            Self::MoveUp => '\u{e495}',
            Self::MoveVertical => '\u{e1c6}',
            Self::Move => '\u{e122}',
            Self::Music2 => '\u{e34d}',
            Self::Music3 => '\u{e34e}',
            Self::Music4 => '\u{e34f}',
            Self::Music => '\u{e123}',
            Self::Navigation2Off => '\u{e2a6}',
            Self::Navigation2 => '\u{e125}',
            Self::NavigationOff => '\u{e2a7}',
            Self::Navigation => '\u{e124}',
            Self::Network => '\u{e126}',
            Self::Newspaper => '\u{e34b}',
            Self::Nfc => '\u{e3c6}',
            Self::NotebookPen => '\u{e59a}',
            Self::NotebookTabs => '\u{e59b}',
            Self::NotebookText => '\u{e59c}',
            Self::Notebook => '\u{e599}',
            Self::NotepadTextDashed => '\u{e59e}',
            Self::NotepadText => '\u{e59d}',
            Self::NutOff => '\u{e39f}',
            Self::Nut => '\u{e39e}',
            Self::OctagonAlert => '\u{e128}',
            Self::OctagonPause => '\u{e21a}',
            Self::OctagonX => '\u{e129}',
            Self::Octagon => '\u{e127}',
            Self::Option => '\u{e1f6}',
            Self::Orbit => '\u{e3ea}',
            Self::Package2 => '\u{e343}',
            Self::PackageCheck => '\u{e265}',
            Self::PackageMinus => '\u{e266}',
            Self::PackageOpen => '\u{e2cb}',
            Self::PackagePlus => '\u{e267}',
            Self::PackageSearch => '\u{e268}',
            Self::PackageX => '\u{e269}',
            Self::Package => '\u{e12a}',
            Self::PaintBucket => '\u{e2e5}',
            Self::PaintRoller => '\u{e5a2}',
            Self::Paintbrush2 => '\u{e2e7}',
            Self::Paintbrush => '\u{e2e6}',
            Self::Palette => '\u{e1db}',
            Self::PanelBottomClose => '\u{e431}',
            Self::PanelBottomDashed => '\u{e432}',
            Self::PanelBottomOpen => '\u{e433}',
            Self::PanelBottom => '\u{e430}',
            Self::PanelLeftClose => '\u{e21b}',
            Self::PanelLeftDashed => '\u{e434}',
            Self::PanelLeftOpen => '\u{e21c}',
            Self::PanelLeft => '\u{e12b}',
            Self::PanelRightClose => '\u{e436}',
            Self::PanelRightDashed => '\u{e437}',
            Self::PanelRightOpen => '\u{e438}',
            Self::PanelRight => '\u{e435}',
            Self::PanelTopClose => '\u{e43a}',
            Self::PanelTopDashed => '\u{e43b}',
            Self::PanelTopOpen => '\u{e43c}',
            Self::PanelTop => '\u{e439}',
            Self::PanelsLeftBottom => '\u{e12c}',
            Self::PanelsRightBottom => '\u{e58c}',
            Self::PanelsTopLeft => '\u{e12d}',
            Self::Paperclip => '\u{e12e}',
            Self::Parentheses => '\u{e448}',
            Self::ParkingMeter => '\u{e504}',
            Self::PartyPopper => '\u{e346}',
            Self::Pause => '\u{e12f}',
            Self::PawPrint => '\u{e4f9}',
            Self::PcCase => '\u{e44a}',
            Self::PenLine => '\u{e131}',
            Self::PenTool => '\u{e132}',
            Self::Pen => '\u{e130}',
            Self::PencilLine => '\u{e4f4}',
            Self::PencilRuler => '\u{e4f5}',
            Self::Pencil => '\u{e1f7}',
            Self::Pentagon => '\u{e52f}',
            Self::Percent => '\u{e133}',
            Self::PersonStanding => '\u{e21d}',
            Self::PhoneCall => '\u{e135}',
            Self::PhoneForwarded => '\u{e136}',
            Self::PhoneIncoming => '\u{e137}',
            Self::PhoneMissed => '\u{e138}',
            Self::PhoneOff => '\u{e139}',
            Self::PhoneOutgoing => '\u{e13a}',
            Self::Phone => '\u{e134}',
            Self::Pi => '\u{e476}',
            Self::Piano => '\u{e565}',
            Self::Pickaxe => '\u{e5ca}',
            Self::PictureInPicture2 => '\u{e3b2}',
            Self::PictureInPicture => '\u{e3b1}',
            Self::PieChart => '\u{e13b}',
            Self::PiggyBank => '\u{e13c}',
            Self::PilcrowLeft => '\u{e5e0}',
            Self::PilcrowRight => '\u{e5e1}',
            Self::Pilcrow => '\u{e3a6}',
            Self::Pill => '\u{e3c0}',
            Self::PinOff => '\u{e2b5}',
            Self::Pin => '\u{e258}',
            Self::Pipette => '\u{e13d}',
            Self::Pizza => '\u{e357}',
            Self::PlaneLanding => '\u{e3d0}',
            Self::PlaneTakeoff => '\u{e3d1}',
            Self::Plane => '\u{e1dc}',
            Self::Play => '\u{e13e}',
            Self::Plug2 => '\u{e383}',
            Self::PlugZap2 => '\u{e460}',
            Self::PlugZap => '\u{e20f}',
            Self::Plug => '\u{e382}',
            Self::Plus => '\u{e13f}',
            Self::PocketKnife => '\u{e4a4}',
            Self::Pocket => '\u{e140}',
            Self::Podcast => '\u{e1f8}',
            Self::PointerOff => '\u{e583}',
            Self::Pointer => '\u{e1e6}',
            Self::Popcorn => '\u{e4c2}',
            Self::Popsicle => '\u{e4c3}',
            Self::PoundSterling => '\u{e141}',
            Self::PowerOff => '\u{e207}',
            Self::Power => '\u{e142}',
            Self::Presentation => '\u{e4b2}',
            Self::Printer => '\u{e143}',
            Self::Projector => '\u{e4b3}',
            Self::Proportions => '\u{e5d3}',
            Self::Puzzle => '\u{e29b}',
            Self::Pyramid => '\u{e530}',
            Self::QrCode => '\u{e1dd}',
            Self::Quote => '\u{e238}',
            Self::Rabbit => '\u{e4fa}',
            Self::Radar => '\u{e49b}',
            Self::Radiation => '\u{e446}',
            Self::Radical => '\u{e5c6}',
            Self::RadioReceiver => '\u{e1f9}',
            Self::RadioTower => '\u{e408}',
            Self::Radio => '\u{e144}',
            Self::Radius => '\u{e531}',
            Self::RailSymbol => '\u{e505}',
            Self::Rainbow => '\u{e4c6}',
            Self::Rat => '\u{e3ef}',
            Self::Ratio => '\u{e4ec}',
            Self::ReceiptCent => '\u{e5a9}',
            Self::ReceiptEuro => '\u{e5aa}',
            Self::ReceiptIndianRupee => '\u{e5ab}',
            Self::ReceiptJapaneseYen => '\u{e5ac}',
            Self::ReceiptPoundSterling => '\u{e5ad}',
            Self::ReceiptRussianRuble => '\u{e5ae}',
            Self::ReceiptSwissFranc => '\u{e5af}',
            Self::ReceiptText => '\u{e5b0}',
            Self::Receipt => '\u{e3d6}',
            Self::RectangleEllipsis => '\u{e21e}',
            Self::RectangleHorizontal => '\u{e379}',
            Self::RectangleVertical => '\u{e37a}',
            Self::Recycle => '\u{e2e8}',
            Self::Redo2 => '\u{e29f}',
            Self::RedoDot => '\u{e454}',
            Self::Redo => '\u{e145}',
            Self::RefreshCcwDot => '\u{e4b6}',
            Self::RefreshCcw => '\u{e146}',
            Self::RefreshCwOff => '\u{e49c}',
            Self::RefreshCw => '\u{e147}',
            Self::Refrigerator => '\u{e37e}',
            Self::Regex => '\u{e1fa}',
            Self::RemoveFormatting => '\u{e3b6}',
            Self::Repeat1 => '\u{e1fb}',
            Self::Repeat2 => '\u{e415}',
            Self::Repeat => '\u{e148}',
            Self::ReplaceAll => '\u{e3df}',
            Self::Replace => '\u{e3de}',
            Self::ReplyAll => '\u{e22a}',
            Self::Reply => '\u{e229}',
            Self::Rewind => '\u{e149}',
            Self::Ribbon => '\u{e55c}',
            Self::Rocket => '\u{e285}',
            Self::RockingChair => '\u{e232}',
            Self::RollerCoaster => '\u{e484}',
            Self::Rotate3D => '\u{e2e9}',
            Self::RotateCcwSquare => '\u{e5d4}',
            Self::RotateCcw => '\u{e14a}',
            Self::RotateCwSquare => '\u{e5d5}',
            Self::RotateCw => '\u{e14b}',
            Self::RouteOff => '\u{e543}',
            Self::Route => '\u{e542}',
            Self::Router => '\u{e3c2}',
            Self::Rows2 => '\u{e43d}',
            Self::Rows3 => '\u{e58e}',
            Self::Rows4 => '\u{e58f}',
            Self::Rss => '\u{e14c}',
            Self::Ruler => '\u{e14d}',
            Self::RussianRuble => '\u{e14e}',
            Self::Sailboat => '\u{e381}',
            Self::Salad => '\u{e3ab}',
            Self::Sandwich => '\u{e3ac}',
            Self::SatelliteDish => '\u{e44c}',
            Self::Satellite => '\u{e44b}',
            Self::SaveAll => '\u{e413}',
            Self::Save => '\u{e14f}',
            Self::Scale3D => '\u{e2ea}',
            Self::Scale => '\u{e211}',
            Self::Scaling => '\u{e2eb}',
            Self::ScanBarcode => '\u{e539}',
            Self::ScanEye => '\u{e53a}',
            Self::ScanFace => '\u{e374}',
            Self::ScanLine => '\u{e257}',
            Self::ScanSearch => '\u{e53b}',
            Self::ScanText => '\u{e53c}',
            Self::Scan => '\u{e256}',
            Self::ScatterChart => '\u{e48e}',
            Self::School => '\u{e3e6}',
            Self::ScissorsLineDashed => '\u{e4ed}',
            Self::Scissors => '\u{e150}',
            Self::ScreenShareOff => '\u{e152}',
            Self::ScreenShare => '\u{e151}',
            Self::ScrollText => '\u{e463}',
            Self::Scroll => '\u{e2ec}',
            Self::SearchCheck => '\u{e4ae}',
            Self::SearchCode => '\u{e4af}',
            Self::SearchSlash => '\u{e4b0}',
            Self::SearchX => '\u{e4b1}',
            Self::Search => '\u{e153}',
            Self::SendHorizontal => '\u{e4f6}',
            Self::SendToBack => '\u{e4f7}',
            Self::Send => '\u{e154}',
            Self::SeparatorHorizontal => '\u{e1c7}',
            Self::SeparatorVertical => '\u{e1c8}',
            Self::ServerCog => '\u{e344}',
            Self::ServerCrash => '\u{e1e7}',
            Self::ServerOff => '\u{e1e8}',
            Self::Server => '\u{e155}',
            Self::Settings2 => '\u{e244}',
            Self::Settings => '\u{e156}',
            Self::Shapes => '\u{e4b7}',
            Self::Share2 => '\u{e158}',
            Self::Share => '\u{e157}',
            Self::Sheet => '\u{e159}',
            Self::Shell => '\u{e4fb}',
            Self::ShieldAlert => '\u{e1fc}',
            Self::ShieldBan => '\u{e15b}',
            Self::ShieldCheck => '\u{e1fd}',
            Self::ShieldEllipsis => '\u{e51a}',
            Self::ShieldHalf => '\u{e51b}',
            Self::ShieldMinus => '\u{e51c}',
            Self::ShieldOff => '\u{e15c}',
            Self::ShieldPlus => '\u{e51d}',
            Self::ShieldQuestion => '\u{e412}',
            Self::ShieldX => '\u{e1fe}',
            Self::Shield => '\u{e15a}',
            Self::ShipWheel => '\u{e506}',
            Self::Ship => '\u{e3bd}',
            Self::Shirt => '\u{e1c9}',
            Self::ShoppingBag => '\u{e15d}',
            Self::ShoppingBasket => '\u{e4ee}',
            Self::ShoppingCart => '\u{e15e}',
            Self::Shovel => '\u{e15f}',
            Self::ShowerHead => '\u{e37f}',
            Self::Shrink => '\u{e21f}',
            Self::Shrub => '\u{e2ed}',
            Self::Shuffle => '\u{e160}',
            Self::Sigma => '\u{e1ff}',
            Self::SignalHigh => '\u{e25f}',
            Self::SignalLow => '\u{e260}',
            Self::SignalMedium => '\u{e261}',
            Self::SignalZero => '\u{e262}',
            Self::Signal => '\u{e25e}',
            Self::SignpostBig => '\u{e545}',
            Self::Signpost => '\u{e544}',
            Self::Siren => '\u{e2ee}',
            Self::SkipBack => '\u{e161}',
            Self::SkipForward => '\u{e162}',
            Self::Skull => '\u{e220}',
            Self::Slack => '\u{e163}',
            Self::Slash => '\u{e521}',
            Self::Slice => '\u{e2ef}',
            Self::SlidersHorizontal => '\u{e299}',
            Self::SlidersVertical => '\u{e164}',
            Self::SmartphoneCharging => '\u{e22d}',
            Self::SmartphoneNfc => '\u{e3c7}',
            Self::Smartphone => '\u{e165}',
            Self::SmilePlus => '\u{e300}',
            Self::Smile => '\u{e166}',
            Self::Snail => '\u{e4fc}',
            Self::Snowflake => '\u{e167}',
            Self::Sofa => '\u{e2c3}',
            Self::Soup => '\u{e3ad}',
            Self::Space => '\u{e3e0}',
            Self::Spade => '\u{e49d}',
            Self::Sparkle => '\u{e482}',
            Self::Sparkles => '\u{e416}',
            Self::Speaker => '\u{e168}',
            Self::Speech => '\u{e522}',
            Self::SpellCheck2 => '\u{e49f}',
            Self::SpellCheck => '\u{e49e}',
            Self::Spline => '\u{e38e}',
            Self::Split => '\u{e444}',
            Self::SprayCan => '\u{e499}',
            Self::Sprout => '\u{e1e9}',
            Self::SquareActivity => '\u{e4b8}',
            Self::SquareArrowDownLeft => '\u{e4b9}',
            Self::SquareArrowDownRight => '\u{e4ba}',
            Self::SquareArrowDown => '\u{e42b}',
            Self::SquareArrowLeft => '\u{e42c}',
            Self::SquareArrowOutDownLeft => '\u{e5a5}',
            Self::SquareArrowOutDownRight => '\u{e5a6}',
            Self::SquareArrowOutUpLeft => '\u{e5a7}',
            Self::SquareArrowOutUpRight => '\u{e5a8}',
            Self::SquareArrowRight => '\u{e42d}',
            Self::SquareArrowUpLeft => '\u{e4bb}',
            Self::SquareArrowUpRight => '\u{e4bc}',
            Self::SquareArrowUp => '\u{e42e}',
            Self::SquareAsterisk => '\u{e16a}',
            Self::SquareBottomDashedScissors => '\u{e4ef}',
            Self::SquareCheckBig => '\u{e16b}',
            Self::SquareCheck => '\u{e55d}',
            Self::SquareChevronDown => '\u{e3d2}',
            Self::SquareChevronLeft => '\u{e3d3}',
            Self::SquareChevronRight => '\u{e3d4}',
            Self::SquareChevronUp => '\u{e3d5}',
            Self::SquareCode => '\u{e16c}',
            Self::SquareDashedBottomCode => '\u{e4c5}',
            Self::SquareDashedBottom => '\u{e4c4}',
            Self::SquareDashedKanban => '\u{e16d}',
            Self::SquareDashedMousePointer => '\u{e50d}',
            Self::SquareDivide => '\u{e16e}',
            Self::SquareDot => '\u{e16f}',
            Self::SquareEqual => '\u{e170}',
            Self::SquareFunction => '\u{e22c}',
            Self::SquareGanttChart => '\u{e171}',
            Self::SquareKanban => '\u{e172}',
            Self::SquareLibrary => '\u{e553}',
            Self::SquareM => '\u{e507}',
            Self::SquareMenu => '\u{e457}',
            Self::SquareMinus => '\u{e173}',
            Self::SquareMousePointer => '\u{e200}',
            Self::SquareParkingOff => '\u{e3cf}',
            Self::SquareParking => '\u{e3ce}',
            Self::SquarePen => '\u{e174}',
            Self::SquarePercent => '\u{e520}',
            Self::SquarePi => '\u{e48c}',
            Self::SquarePilcrow => '\u{e48f}',
            Self::SquarePlay => '\u{e485}',
            Self::SquarePlus => '\u{e175}',
            Self::SquarePower => '\u{e555}',
            Self::SquareRadical => '\u{e5c7}',
            Self::SquareScissors => '\u{e4f0}',
            Self::SquareSigma => '\u{e48d}',
            Self::SquareSlash => '\u{e176}',
            Self::SquareSplitHorizontal => '\u{e3b9}',
            Self::SquareSplitVertical => '\u{e3ba}',
            Self::SquareStack => '\u{e4a6}',
            Self::SquareTerminal => '\u{e208}',
            Self::SquareUserRound => '\u{e46a}',
            Self::SquareUser => '\u{e469}',
            Self::SquareX => '\u{e177}',
            Self::Square => '\u{e169}',
            Self::Squircle => '\u{e57e}',
            Self::Squirrel => '\u{e4a3}',
            Self::Stamp => '\u{e3be}',
            Self::StarHalf => '\u{e209}',
            Self::StarOff => '\u{e2af}',
            Self::Star => '\u{e178}',
            Self::StepBack => '\u{e3ec}',
            Self::StepForward => '\u{e3ed}',
            Self::Stethoscope => '\u{e2f0}',
            Self::Sticker => '\u{e301}',
            Self::StickyNote => '\u{e302}',
            Self::Store => '\u{e3e7}',
            Self::StretchHorizontal => '\u{e27b}',
            Self::StretchVertical => '\u{e27c}',
            Self::Strikethrough => '\u{e179}',
            Self::Subscript => '\u{e25b}',
            Self::SunDim => '\u{e298}',
            Self::SunMedium => '\u{e2b0}',
            Self::SunMoon => '\u{e2b1}',
            Self::SunSnow => '\u{e375}',
            Self::Sun => '\u{e17a}',
            Self::Sunrise => '\u{e17b}',
            Self::Sunset => '\u{e17c}',
            Self::Superscript => '\u{e25d}',
            Self::SwatchBook => '\u{e5a3}',
            Self::SwissFranc => '\u{e17d}',
            Self::SwitchCamera => '\u{e17e}',
            Self::Sword => '\u{e2b2}',
            Self::Swords => '\u{e2b3}',
            Self::Syringe => '\u{e2f1}',
            Self::Table2 => '\u{e2f8}',
            Self::TableCellsMerge => '\u{e5cb}',
            Self::TableCellsSplit => '\u{e5cc}',
            Self::TableColumnsSplit => '\u{e5cd}',
            Self::TableProperties => '\u{e4df}',
            Self::TableRowsSplit => '\u{e5ce}',
            Self::Table => '\u{e17f}',
            Self::TabletSmartphone => '\u{e50e}',
            Self::Tablet => '\u{e180}',
            Self::Tablets => '\u{e3c1}',
            Self::Tag => '\u{e181}',
            Self::Tags => '\u{e35f}',
            Self::Tally1 => '\u{e4da}',
            Self::Tally2 => '\u{e4db}',
            Self::Tally3 => '\u{e4dc}',
            Self::Tally4 => '\u{e4dd}',
            Self::Tally5 => '\u{e4de}',
            Self::Tangent => '\u{e532}',
            Self::Target => '\u{e182}',
            Self::Telescope => '\u{e5c9}',
            Self::TentTree => '\u{e53f}',
            Self::Tent => '\u{e226}',
            Self::Terminal => '\u{e183}',
            Self::TestTubeDiagonal => '\u{e40a}',
            Self::TestTube => '\u{e409}',
            Self::TestTubes => '\u{e40b}',
            Self::TextCursorInput => '\u{e264}',
            Self::TextCursor => '\u{e263}',
            Self::TextQuote => '\u{e4a2}',
            Self::TextSearch => '\u{e5b1}',
            Self::TextSelect => '\u{e3e1}',
            Self::Text => '\u{e3ee}',
            Self::Theater => '\u{e526}',
            Self::ThermometerSnowflake => '\u{e185}',
            Self::ThermometerSun => '\u{e186}',
            Self::Thermometer => '\u{e184}',
            Self::ThumbsDown => '\u{e187}',
            Self::ThumbsUp => '\u{e188}',
            Self::TicketCheck => '\u{e5b2}',
            Self::TicketMinus => '\u{e5b3}',
            Self::TicketPercent => '\u{e5b4}',
            Self::TicketPlus => '\u{e5b5}',
            Self::TicketSlash => '\u{e5b6}',
            Self::TicketX => '\u{e5b7}',
            Self::Ticket => '\u{e20d}',
            Self::TimerOff => '\u{e248}',
            Self::TimerReset => '\u{e235}',
            Self::Timer => '\u{e1de}',
            Self::ToggleLeft => '\u{e189}',
            Self::ToggleRight => '\u{e18a}',
            Self::Tornado => '\u{e217}',
            Self::Torus => '\u{e533}',
            Self::TouchpadOff => '\u{e44e}',
            Self::Touchpad => '\u{e44d}',
            Self::TowerControl => '\u{e3bf}',
            Self::ToyBrick => '\u{e34a}',
            Self::Tractor => '\u{e508}',
            Self::TrafficCone => '\u{e509}',
            Self::TrainFrontTunnel => '\u{e50b}',
            Self::TrainFront => '\u{e50a}',
            Self::TrainTrack => '\u{e50c}',
            Self::TramFront => '\u{e2a8}',
            Self::Trash2 => '\u{e18c}',
            Self::Trash => '\u{e18b}',
            Self::TreeDeciduous => '\u{e2f2}',
            Self::TreePalm => '\u{e280}',
            Self::TreePine => '\u{e2f3}',
            Self::Trees => '\u{e2f4}',
            Self::Trello => '\u{e18d}',
            Self::TrendingDown => '\u{e18e}',
            Self::TrendingUp => '\u{e18f}',
            Self::TriangleAlert => '\u{e191}',
            Self::TriangleRight => '\u{e4f1}',
            Self::Triangle => '\u{e190}',
            Self::Trophy => '\u{e376}',
            Self::Truck => '\u{e192}',
            Self::Turtle => '\u{e4fd}',
            Self::Tv2 => '\u{e201}',
            Self::Tv => '\u{e193}',
            Self::Twitch => '\u{e194}',
            Self::Twitter => '\u{e195}',
            Self::Type => '\u{e196}',
            Self::UmbrellaOff => '\u{e547}',
            Self::Umbrella => '\u{e197}',
            Self::Underline => '\u{e198}',
            Self::Undo2 => '\u{e2a0}',
            Self::UndoDot => '\u{e455}',
            Self::Undo => '\u{e199}',
            Self::UnfoldHorizontal => '\u{e441}',
            Self::UnfoldVertical => '\u{e442}',
            Self::Ungroup => '\u{e46b}',
            Self::University => '\u{e3e8}',
            Self::Unlink2 => '\u{e19b}',
            Self::Unlink => '\u{e19a}',
            Self::Unplug => '\u{e461}',
            Self::Upload => '\u{e19c}',
            Self::Usb => '\u{e359}',
            Self::UserCheck => '\u{e19e}',
            Self::UserCog => '\u{e345}',
            Self::UserMinus => '\u{e19f}',
            Self::UserPlus => '\u{e1a0}',
            Self::UserRoundCheck => '\u{e46d}',
            Self::UserRoundCog => '\u{e46e}',
            Self::UserRoundMinus => '\u{e46f}',
            Self::UserRoundPlus => '\u{e470}',
            Self::UserRoundSearch => '\u{e57c}',
            Self::UserRoundX => '\u{e471}',
            Self::UserRound => '\u{e46c}',
            Self::UserSearch => '\u{e57d}',
            Self::UserX => '\u{e1a1}',
            Self::User => '\u{e19d}',
            Self::UsersRound => '\u{e472}',
            Self::Users => '\u{e1a2}',
            Self::UtensilsCrossed => '\u{e2f6}',
            Self::Utensils => '\u{e2f5}',
            Self::UtilityPole => '\u{e3c5}',
            Self::Variable => '\u{e477}',
            Self::Vault => '\u{e593}',
            Self::Vegan => '\u{e3a0}',
            Self::VenetianMask => '\u{e2a9}',
            Self::VibrateOff => '\u{e29c}',
            Self::Vibrate => '\u{e222}',
            Self::VideoOff => '\u{e1a4}',
            Self::Video => '\u{e1a3}',
            Self::Videotape => '\u{e4cf}',
            Self::View => '\u{e1a5}',
            Self::Voicemail => '\u{e1a6}',
            Self::Volume1 => '\u{e1a8}',
            Self::Volume2 => '\u{e1a9}',
            Self::VolumeX => '\u{e1aa}',
            Self::Volume => '\u{e1a7}',
            Self::Vote => '\u{e3b0}',
            Self::WalletCards => '\u{e4d0}',
            Self::WalletMinimal => '\u{e4d1}',
            Self::Wallet => '\u{e202}',
            Self::Wallpaper => '\u{e44f}',
            Self::WandSparkles => '\u{e35a}',
            Self::Wand => '\u{e245}',
            Self::Warehouse => '\u{e3e9}',
            Self::WashingMachine => '\u{e594}',
            Self::Watch => '\u{e1ab}',
            Self::Waves => '\u{e282}',
            Self::Waypoints => '\u{e546}',
            Self::Webcam => '\u{e203}',
            Self::WebhookOff => '\u{e5bb}',
            Self::Webhook => '\u{e377}',
            Self::Weight => '\u{e534}',
            Self::WheatOff => '\u{e3a2}',
            Self::Wheat => '\u{e3a1}',
            Self::WholeWord => '\u{e3e2}',
            Self::WifiOff => '\u{e1ad}',
            Self::Wifi => '\u{e1ac}',
            Self::Wind => '\u{e1ae}',
            Self::WineOff => '\u{e3a3}',
            Self::Wine => '\u{e2f7}',
            Self::Workflow => '\u{e429}',
            Self::Worm => '\u{e5de}',
            Self::WrapText => '\u{e247}',
            Self::Wrench => '\u{e1af}',
            Self::X => '\u{e1b0}',
            Self::Youtube => '\u{e1b1}',
            Self::ZapOff => '\u{e1b3}',
            Self::Zap => '\u{e1b2}',
            Self::ZoomIn => '\u{e1b4}',
            Self::ZoomOut => '\u{e1b5}',
        }.fmt(f)
    }
}


/// Retrieves the font to be used in `.font(lucide_font())`
/// 
/// ```rust
/// text(Lucide::AArrowDown).font(lucide_font())
/// ```
pub fn lucide_font() -> Font {
    Font::with_name("lucide")
}

/// Loads the source so that it can be registered at the beginning of iced
/// 
/// See an example of how to do this by [clicking here](https://github.com/iced-box/iced-box/tree/main/examples/icons)
pub fn load_lucide_font() -> &'static [u8] {
    include_bytes!("assets/lucide-icons.ttf").as_slice()
}
